### ISSUE TITLE
Handle semantics of unique_ptr<xxx> properly

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#1]
For Wrapper<XXXX>    handle semantics so that the wrapper takes ownership of a unique_ptr and gives up ownership when it returns the object to C++

Check out asttooling/translators.h   - this code is currently commented out but it mentions the idea
#if 0 // You will need the following from_object and to_object to wrap ClangTool::buildASTs
    // You will also need to make clbind::Wrappers do the right thing with std::unique_ptrs
    //
    template <>
    struct from_object<std::vector<std::unique_ptr<clang::ASTUnit>>&>
    {
        typedef std::vector<std::unique_ptr<clang::ASTUnit>>&   DeclareType;
        std::vector<std::unique_ptr<clang::ASTUnit>>    _Temp;
        DeclareType     _v;
        from_object(core::T_sp o) : _v(_Temp)
        {
            if ( o.nilp() ) {
                this->_v.clear();
                return;
            } else if ( core::VectorObjects_sp vo = o.asOrNull<core::VectorObjects_O>() ) {
                this->_v.clear();
                this->_v.resize(vo->length());
                for ( int i(0), iEnd(vo->length()); i<iEnd; i++ ) {
                    this->_v[i] = vo->elt(i).as<clbind::Wrapper<clang::ASTUnit,std::unique_ptr<clang::ASTUnit> > >();
                }
                return;
            }
            SIMPLE_ERROR(BF("Could not convert argument %s into std::vector<clang::ASTUnit*>") % _rep_(o));
        }
    };

**Comment by Shinmera** [comment]
Irrelevant.
