### ISSUE TITLE
function-lambda-expression crashes

### ISSUE THREAD

**Issue by stassats** [drmeister/clasp#101]
(function-lambda-expression #'list)

Illegal cast of tagged_functor
src/core/foundation.cc:300 dbg_hook(...) was called

Illegal cast of tagged_functor
src/core/foundation.cc:300 dbg_hook(...) was called

"# 18/b@0x7f7c87a00198       executables.cc   262/0   COMMON-LISP:FUNCTION-LAMBDA-EXPRESSION
"

**Comment by stassats** [comment]
Has been fixed.

**Comment by Shinmera** [comment]
Cannot confirm on b05884f.
```
> (function-lambda-expression #'list)

NIL
T
LIST
```
