### ISSUE TITLE
printing some floats casues an FPE

### ISSUE THREAD

**Issue by stassats** [drmeister/clasp#104]
(princ 0.005109d0)
zsh: floating point exception  clasp

**Comment by stassats** [comment]
#0  0x00007fadb65a567a in __gmp_exception () from /usr/lib/x86_64-linux-gnu/libgmp.so.10
#1  0x00007fadb65a56ae in __gmp_divide_by_zero () from /usr/lib/x86_64-linux-gnu/libgmp.so.10
#2  0x00007fadb65c0545 in __gmpz_tdiv_qr () from /usr/lib/x86_64-linux-gnu/libgmp.so.10
#3  0x00007fadb65b50f1 in __gmpz_fdiv_qr () from /usr/lib/x86_64-linux-gnu/libgmp.so.10
#4  0x0000000000cb2df4 in core::big_floor (a=..., b=...) at src/core/bignum.cc:256
#5  0x00000000010bede4 in _clasp_big_floor (a=..., b=..., rP=<optimized out>) at include/clasp/core/bignum.h:184
#6  core::clasp_floor2 (x=..., y=...) at src/core/num_co.cc:303
#7  0x00000000010c196b in core::clasp_truncate2 (x=..., y=...) at src/core/num_co.cc:709
#8  0x0000000000e4afe6 in generate (digits=..., approx=<optimized out>) at src/core/float_to_digits.cc:164
#9  core::core_float_to_digits (tdigits=..., number=..., position=..., relativep=...) at src/core/float_to_digits.cc:254
#10 0x0000000001090b51 in core::core_float_to_string_free (buffer_or_nil=..., number=..., e_min=..., e_max=...) at src/core/float_to_string.cc:119
#11 0x0000000000dfc670 in core::write_float (f=..., stream=...) at src/core/write_ugly.cc:447
#12 0x0000000000dfb6a2 in core::write_ugly_object (x=..., stream=...) at src/core/write_ugly.cc:474
#13 0x00000000010cfa5a in core::write_object (x=..., stream=...) at src/core/write_object.cc:166

**Comment by drmeister** [comment]
Weird   (princ 0.0123d0) works    (princ 0.005123d0) fails as above

**Comment by stassats** [comment]
Resolved now.
