### ISSUE TITLE
Macro lambda lists do not accept dotted lists.

### ISSUE THREAD

**Issue by stassats** [drmeister/clasp#106]
(defmacro foo (x . y))
(define-compiler-macro x (x . y))
(macrolet ((x (x . y))))
COMMON-LISP:TYPE-ERROR :initializers (:DATUM Y :EXPECTED-TYPE COMMON-LISP:LIST  )

**Comment by drmeister** [comment]
This happens in cclasp and bclasp

**Comment by stassats** [comment]
Because (last '(x . y)) => error

**Comment by drmeister** [comment]
Also because (butlast '(x . y) 0 ) --> error

**Comment by drmeister** [comment]
Fixed LAST, BUTLAST and NBUTLAST

**Comment by drmeister** [comment]
Oh  and (defmacro foo ( x . y )) works now
