### ISSUE TITLE
with-packages-iterator and hash table iteration is too slow

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#109]
stassats reports that for Slime on Clasp, once package iteration is fast, the disabled feature (informing about non-standard macros for indentation) can be turned on.

(time (do-symbols (symbol (find-package :cl-user)))) => real time          : 0.207 secs
That is too slow

**Comment by Shinmera** [comment]
Cannot confirm on b05884f.
```
ASDF/USER> (time (do-symbols (symbol (find-package :cl-user))))
real time          : 0.074 secs
run time           : 0.073 secs
GC bytes consed    : 6518528 bytes
Clasp bytes consed : 2306672 bytes
LLVM time          : 0.000 secs
LLVM compiles      : 0
```
Though it could certainly be improved still.

**Comment by Shinmera** [comment]
Closing this as the issue seems to be just clasp being slow in general now (0.046s for the above snippet) rather than being specifically tied to packages and symbols.
