### ISSUE TITLE
compiling a .lisp file produces gigantic output files

### ISSUE THREAD

**Issue by k--r** [drmeister/clasp#112]
i'm using (compile-file ...) to compile a tiny test file with 2 functions in it.  the process generates several output files that are many megabytes in size !  this is a few order of magnitude bigger than the original source.  there is some huge baggage attached.  this is an ls -l :

-rw-rw-r--  1 kr kr   12988 Jul  3 20:03 test-file.bc
-rwxrwxr-x  1 kr kr 1517990 Jul  3 20:03 test-file.fasl*
-rw-rw-r--  1 kr kr 2409320 Jul  3 20:03 test-file.lbc
-rw-rw-r--  1 kr kr     102 Jul  3 20:03 test-file.lisp
-rw-rw-r--  1 kr kr 2725896 Jul  3 20:03 test-file.o

this happened to a clasp 0.2 build of mine from the master branch about a week ago, and also a recent build from tag 0.3-test-6

it would be good also to have a quick explanation of what all these files are needed for and how they relate to each other.

and ideally, the gigantic baggage should be trimmed off...

**Comment by Shinmera** [comment]
A simple file with just `(defun foo () (print "hi"))` in it produces:
```
4.0K	a.bc
180K	a.fasl
128K	a.lbc
4.0K	a.lisp
280K	a.o
```
Something more complicated like
```
(defstruct (vec (:conc-name NIL)
                (:constructor %vec (vx vy vz))
                (:copier vcopy)
                (:predicate vec-p))
  (vx 0 :type double-float)
  (vy 0 :type double-float)
  (vz 0 :type double-float))

(defmethod print-object ((v vec) stream)
  (if (eql (type-of v) 'vec)
      (print (make-load-form v) stream)
      (call-next-method)))

(defmethod make-load-form ((v vec) &optional env)
  (declare (ignore env))
  `(vec ,(vx v) ,(vy v) ,(vz v)))

(declaim (inline vec))
(declaim (ftype (function (number number number) vec) vec))
(defun vec (x y z)
  (%vec (float x 0.0d0) (float y 0.0d0) (float z 0.0d0)))

(defun ensure-double-float-param (val env)
  (if (constantp val env)
      (typecase val
        (double-float val)
        (real (float val 0.0d0))
        (T `(load-time-value (float ,val 0.0d0))))
      `(float ,val 0.0d0)))
```
Produces still quite manageable sizes:
```
28K	a.bc
208K	a.fasl
200K	a.lbc
4.0K	a.lisp
340K	a.o
```

Considering fixed, though maybe the amount of litter should be reduced.
