### ISSUE TITLE
0.3-test-6-6-gb7fe96f bclasp build drops into the debugger

### ISSUE THREAD

**Issue by Georgiy-Tugai** [drmeister/clasp#114]
```
src/core/exceptions.cc:133 af_signalSimpleError  caught because signal-simple-error is not installed yet
COMMON-LISP:PROGRAM-ERROR
There is no function bound to the symbol FORMATTER-AUX

af_signalSimpleError
src/core/foundation.cc:300 dbg_hook(...) was called

"# 68/b@0x7f94fd9c1d28        exceptions.cc   764/0   SIGNAL-SIMPLE-ERROR
" 
"The following restarts are available:" 
"ABORT      a    Abort to REPL" 
Frame-68-Dbg[1]>
```
Full log of `make clasp-boehm` (75Mb): https://gist.github.com/Georgiy-Tugai/080c1329c947162102e0
or clone `git@gist.github.com:/080c1329c947162102e0.git`

**Comment by drmeister** [comment]
Hmm, I can't open the full log and the error above is too brief.
Could you paste just a few thousand lines above the error?

**Comment by Shinmera** [comment]
Build attempt is too old, the problem is most likely gone by now. If it persists on recent commits, please open a new ticket.
