### ISSUE TITLE
Problem with COMPILE-FILE and EVAL-WHEN

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#116]
foo.lisp:
(eval-when (:compile-toplevel :load-toplevel :execute)
  (compile-file "/tmp/bar.lisp"))
bar.lisp:
(eval-when (:compile-toplevel :load-toplevel :execute)
  (write-line "EVAL"))

(compile-file "/tmp/foo.lisp")
Writing fasl file to: #P"/tmp/bar.fasl"
Linking #P"/tmp/bar.bc"
Linking app-resources:lib;release;intrinsics_bitcode_boehm.o
Running link time optimization module pass manager
Generating object file  /tmp/bar.lbc  -->  /tmp/bar.o  reloc-model: RELOC-MODEL-PIC-
Writing fasl file to: #P"/tmp/foo.fasl"
Linking #P"/tmp/foo.bc"
Linking app-resources:lib;release;intrinsics_bitcode_boehm.o
Running link time optimization module pass manager
Generating object file  /tmp/foo.lbc  -->  /tmp/foo.o  reloc-model: RELOC-MODEL-PIC-
#P"/tmp/foo.fasl"

**Comment by Shinmera** [comment]
Cannot confirm on b05884f.
```
> (compile-file #p"~/a.lisp")
EVAL
Writing fasl file to: #P"/home/linus/b.fasl"
Linking #P"/home/linus/b.bc"
Linking app-resources:lib;release;intrinsics_bitcode_mps.sbc
Generating object file  /home/linus/b.lbc  -->  /home/linus/b.o  reloc-model: RELOC-MODEL-PIC-
Writing fasl file to: #P"/home/linus/a.fasl"
Linking #P"/home/linus/a.bc"
Linking app-resources:lib;release;intrinsics_bitcode_mps.sbc
Generating object file  /home/linus/a.lbc  -->  /home/linus/a.o  reloc-model: RELOC-MODEL-PIC-
#P"/home/linus/a.fasl"
NIL
NIL
> (load #p"~/a.fasl")
EVAL
Writing fasl file to: #P"/home/linus/b.fasl"
Linking #P"/home/linus/b.bc"
Linking app-resources:lib;release;intrinsics_bitcode_mps.sbc
Generating object file  /home/linus/b.lbc  -->  /home/linus/b.o  reloc-model: RELOC-MODEL-PIC-
T
> (load #p"~/b.fasl")
EVAL
T
> 
```
