### ISSUE TITLE
Problem with MACROLET

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#117]
(defun test ()
  (macrolet ((macro ((&key index))))
    (macro (:index 10))))

(compile-file "/tmp/foo.lisp")
;;; Warning: Condition: Undefined function named COMMON-LISP:DECLARE
;;; Warning: Condition: Undefined function named COMMON-LISP:IGNORE

Condition of type: SIMPLE-ERROR
too many arguments supplied

**Comment by Shinmera** [comment]
Cannot confirm on b05884f.
```
> (load #p"~/a.lisp")

T
> (test)

NIL
```
Though loading the file does take an extraordinarily long time.
