### ISSUE TITLE
(setq ..) causes error: Could not update local symbol(*FOO*) because it was not defined

### ISSUE THREAD

**Issue by k--r** [drmeister/clasp#119]
i noticed the following in:
Starting Boehm cclasp 0.3 ... loading image... it takes a few seconds
(built in the newbuild branch a day or 2 ago, post 0.3-test-7 )

if (setq ...) is used before a variable is defined by (defvar ...) or whatever, it breaks now.
for interactive experiments at the repl, this should be perfectly legal common-lisp, and all implementations i know of (except this one) will accept that, though maybe warning.
example:

> (setq *foo* 3)

Debugger received error of type: SIMPLE-PROGRAM-ERROR
Could not update local symbol(*FOO*) because it was not defined
Error flushed.
>

**Comment by Shinmera** [comment]
Cannot confirm on b05884f.
```
> (setq foo 3)
;;; Warning: Condition: Undefined variable named COMMON-LISP-USER::FOO

3
```
