### ISSUE TITLE
Misleading documentation about restarts

### ISSUE THREAD

**Issue by fmitha** [drmeister/clasp#13]
This misleading documentation has been inherited from ecl apparently.
but no reason not to fix it here. I guess one could report it to ecl too,
in case anyone cares.

If I can figure out how to recompile only the common lisp sources,
then i can try patching this. It probably is not hard.

##################################################

faheem@orwell:~/local/clasp/bin$ rlwrap ./clasp_boehm_o 
Starting Clasp 0.1... loading image... it takes a few seconds
Could not find pathname: /home/faheem/.clasprc
Top level.
> (1 1)

Condition of type: SIMPLE-ERROR
obj must be a symbol - instead it is: 1

Available restarts:

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

Broken at frame[29] CORE::REP.
 File: #<CORE:SOURCE-FILE-INFO #P"/home/faheem/local/clasp/Contents/Resources/lisp/kernel/lsp/top.lsp"> (Position #573)
>> 1

1
>> :r1

>

**Comment by Shinmera** [comment]
Clasp makes a little mention about how to invoke restarts now.

**Comment by bamboospirit** [comment]
I agree that ECL's restarts are ambigous
