### ISSUE TITLE
docstrings for functions exposed from c++ not working

### ISSUE THREAD

**Issue by HeyFlash** [drmeister/clasp#144]
clbind provides a mechanism for providing docstrings for the exposed functionality.
However, on the clasp side, documentation always returns nil, not matter what was set on the c++ side.
E.g. with clasp-sfml loaded:
(documentation #'sf:play 'function)
=> nil

**Comment by drmeister** [comment]
Testing a builtin C++ function cl__length...
(documentation 'length 'function) --> "See CLHS length - works with SEQUENCES and ACTIVATION_FRAMEs"

Testing a clbind function exposed in astExpose.cc...
(documentation 'clang-ast:get-type-ptr-or-null 'function) --> "getTypePtrOrNull - returns the most derived Type* ptr or NIL"

**Comment by Shinmera** [comment]
Can confirm fixed on 99669d674a6f2b7ce0a9127cf6537fc03066baa5
