### ISSUE TITLE
Cannot cast tagged_pointer in constructor When Loading a Clbind Library

### ISSUE THREAD

**Issue by Shinmera** [drmeister/clasp#158]
Source files to create the test:
Makefile:
```
export CLANG ?= clang++
export CLASP_CLBIND_LIB ?= $(CLASP_HOME)/build/clasp/Contents/execs/boehm/release/lib/libclasp-clbind.so
export CLASP_INCLUDE ?= $(CLASP_HOME)/include
export OPTIONS += -std=c++11
export OPTIONS += -v
#export OPTIONS += --shared
export OPTIONS += -fPIC
export OPTIONS += -D_TARGET_OS_LINUX
export OPTIONS += -DX86
export OPTIONS += -DNDEBUG
export OPTIONS += -DUSE_BOEHM
export OPTIONS += -DUSE_ALLOCA_FOR_FRAME
export OPTIONS += -D_ADDRESS_MODEL_64
export OPTIONS += -Wno-deprecated-register
export OPTIONS += -I $(CLASP_INCLUDE)
export OPTIONS += -lboost_system
export OPTIONS += -Wl,--start-group
export OPTIONS += $(CLASP_CLBIND_LIB)
export OPTIONS += -Wl,--end-group

membertest: membertest.cc
#	$(CLANG) $(OPTIONS) -o membertest.bundle membertest.cc
	$(CLANG) $(OPTIONS) -c membertest.cc
	$(CLANG) -fPIC -DNDEBUG -shared -Wl,-soname,membertest.bundle -o membertest.bundle membertest.o
```
membertest.cc
```
#include <string>
#include "clasp/clasp.h"
#define EXPORT __attribute__((visibility("default")))

class Message{
public:
  Message(std::string message);
  
  std::string message;
};

Message::Message(std::string message){
  this->message = message;
}

extern "C" {
EXPORT
void CLASP_MAIN(){
  using namespace clbind;
  package("membertest") [
                         class_<Message>("message", no_default_constructor)
                         .def_constructor("make-message",constructor<std::string>())
                         .def_readonly("message", &Message::message)
                         ];
}
}
```
Reproducing:
```
cd clasp-home
mkdir examples/membertest
cd examples/membertest
emacs Makefile membertest.cc
CLASP_HOME=../.. make membertest
../../build/clasp/bin/clasp_boehm_o
(load "membertest.bundle")
(|membertest|:MAKE-MESSAGE "test")
(|membertest|:MESSAGE *)
```

On f20dd7b964a58a70d2b8468b5c426b0a50aea9f8 things work out just as expected. The class is instantiated and returns nicely and I can access the member just fine. All wonderful. However, on later revisions like 7fde5b78e98bf1af8e74f3884815a81db9eeec7e things don't work out so nice. Trying to load the bundle results in
```
Cannot cast tagged_pointer in constructor
../../src/core/foundation.cc:235 dbg_hook(...) was called


Cannot cast tagged_pointer in constructor
../../src/core/foundation.cc:235 dbg_hook(...) was called
```
Commenting out both definitions, recompiling, and then loading it works, so the failure point must be somewhere in the definition mechanism. I haven't bisected the problem quite yet, but will do so once I have the time to and if necessary.

**Comment by drmeister** [comment]
This will help a lot - I'll install a Linux VM and set up a development environment.

**Comment by Shinmera** [comment]
Can't you just try linut? There you already have plenty of commits pre-built that you can test it against to bisect the bug.

**Comment by Shinmera** [comment]
Bisection progress: It's still working on c843b0c1b212c47ccc8149687349a17ff3343d9a and then broken on 2fe2255addc4ead33abeec56bc6ee35f0a6d78ed. The commits that that merge pulled in are not built, so I'll see how much farther I can get.

**Comment by drmeister** [comment]
I think this is fixed now in testing commit 712260b

I have to run to class - I'll edit this comment later to describe the problem more fully

**Comment by drmeister** [comment]
It's fixed in https://github.com/drmeister/clasp/commit/712260b4038b40e04d8928b7183e2af5da416a0d

**Comment by Shinmera** [comment]
Can confirm fixed. @HeyFlash
