### ISSUE TITLE
LLVM 3.8 Support

### ISSUE THREAD

**Issue by Shinmera** [drmeister/clasp#165]
Currently Clasp requires llvm 3.6 to build. More up-to-date distributions like Arch have already updated to llvm 3.7, making building clasp an impossibility without downgrading or using externals-clasp. This kludge should be avoided by upgrading to 3.7 and if possible retaining backwards compatibility with 3.6 for the time being until 3.7 becomes standard.

**Comment by phyrog** [comment]
With LLVM 3.8 released a week ago, is there any progress on this? I would love to play around with clasp, but I am currently unable to build it on Arch (even when using externals-clasp, which is building fine), so any news on this I would be happy to hear.

**Comment by Shinmera** [comment]
@drmeister is currently busy with other large changes in the code base, so things are rather unstable build-wise. After this, the next target is to fix things to work in the very least with externals-clasp again, and after that (but maybe not necessarily immediately) move things forward to support more recent versions of the dependant libraries. The changes between 3.6 and 3.7 (and presumably 3.8 again) are apparently non-trivial, so it is unfortunately not just a matter of updating some headers.

**Comment by phyrog** [comment]
Alright, thanks for the update. I'm in no hurry, so I will just stay tuned for when time comes :) Unfortunately my C++ is a bit rusty, so I can't be of much help.

**Comment by Shinmera** [comment]
The port to LLVM3.8 is "done" on a  conceptual level but currently still broken for standard distributions like what the LLVM debian APTs provide.

**Comment by Shinmera** [comment]
As we are now on LLVM 3.9, this is done. Backwards compat is not feasible.
