### ISSUE TITLE
Get MPS Working Again

### ISSUE THREAD

**Issue by Shinmera** [drmeister/clasp#169]
The Memory Pool System is a central aspect of improving Clasp's overall performance and making it reach its end goals. As such, getting it working again is a must. Currently the MPS is prone to breakage and requires massive amounts of memory to compile, which may or may not be solved by #165, however low(er) memory usage during compilation is a must for MPS to be a workable solution on average systems.

**Comment by rptb1** [comment]
Do we know why the MPS takes so much memory to compile within Clasp?  It's not something we see when compiling MPS with other programs.  To test this, just "cc -c mps.c" in the MPS directory!

**Comment by Shinmera** [comment]
From what I remember --and what I tried to hint at in the ticket-- @drmeister said that simply compiling with llvm3.7 already got rid of the memory problem, so getting that fixed might already be the solution.

**Comment by Shinmera** [comment]
MPS seems to be back up and running now, even if slowly.
I did a quick test while recording peak memory usage and it seems that on a system with around 600mb as the baseline, it capped out at around 4'124mb. Thus a 4Gb requirement for building seems reasonable and sufficiently low to consider this resolved.
