### ISSUE TITLE
Initial make or   make clean; make  complains about missing core_scrape_flag.h file

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#17]
Sometimes if you "make" from the initial cloned repository or you "make clean; make" boost build will complain about a missing .h file.  I think its core_scrape_flag.h but I'm not looking at the error right now.
You can control-C the build and make again and it goes away.   It's something to do with the order things are built by boost build.

**Comment by Shinmera** [comment]
Cannot confirm on b05884f. Running `make` once works fine now.
