### ISSUE TITLE
Clean Up Makefile

### ISSUE THREAD

**Issue by Shinmera** [drmeister/clasp#170]
The current makefile is rather littered with testing targets and generally pretty unstructured. In order to allow a more informative build with Autobuild's new staging mechanism, and to allow controlling the build itself more directly by hand, it should be cleaned up and targets should be created to properly reflect the individual stages that the build process undergoes.

**Comment by Shinmera** [comment]
@drmeister Could you quickly go through the existing makefile and list the targets that you sometimes call yourself by hand so I know which ones to remove and which ones to preserve?

**Comment by Georgiy-Tugai** [comment]
I'm currently stress-testing the Makefile by attempting to compile Clasp under NixOS, in which only `/bin/sh` and `/usr/bin/env` are in their usual locations. The distribution sets environment variables (`PATH`, `CFLAGS` etc.) to allow builds to find applications and libraries in their hashed directories; thus, many assumptions made by the build process may be dragged into the light.

**Comment by Georgiy-Tugai** [comment]
I have successfully built Clasp on NixOS, and #171 (already merged) has the Makefile changes needed to fix most of the assumptions discovered.

**Comment by drmeister** [comment]
There are two makefiles that matter.    clasp/makefile and clasp/src/main/makefile.

I removed a bunch of what I think are useless build targets from clasp/makefile.
Do you need me to do the same for clasp/src/main/makefile?  Thats more of a development makefile.

**Comment by Shinmera** [comment]
No, I only want to refactor the main makefile.

**Comment by Shinmera** [comment]
@attila-lendvai is in the process of getting rid of the Makefile entirely.

**Comment by attila-lendvai** [comment]
progress is available at: https://github.com/attila-lendvai/clasp/commits/build-cleanup
