### ISSUE TITLE
fatal error: 'boost/format.hpp' file not found

### ISSUE THREAD

**Issue by lewisde** [drmeister/clasp#172]
OS X 10.11.1
boost-1.59.0 already installed

Is there an export I need to do?

**Comment by Georgiy-Tugai** [comment]
Please run `git describe --always` in your clasp checkout and let us know what the output is.

**Comment by lewisde** [comment]
➜  clasp git:(master) git describe --always
0.4.0
➜  clasp git:(master) git pull origin master
From https://github.com/drmeister/clasp
 * branch            master     -> FETCH_HEAD
Already up-to-date.
➜  clasp git:(master)

**Comment by Shinmera** [comment]
Did you follow the compilation instructions in the readme?  
Did you install the dependencies as listed in the section?  
Did you compile externals-clasp and link to it in the `local.config`?  
What exactly is the build log you're getting?
