### ISSUE TITLE
Remove useless files

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#173]
There's nothing like inviting the neighbors over and have them comment on the untidiness of ones home to motivate one to clean house.

**Comment by Shinmera** [comment]
How is this different from #45 and #41? What exactly should be cleaned up?
Please specify so that this can be confirmed and closed at a distinguishable point in time.

**Comment by drmeister** [comment]
#41 and #45 are equivalent to this.   #88 is a separate issue

**Comment by Shinmera** [comment]
Dupe of #41
