### ISSUE TITLE
Execvp Reurns With 'No such file or directory' When Compiling Slime's packages.lisp

### ISSUE THREAD

**Issue by drjdn** [drmeister/clasp#176]
I'm having trouble getting slime to work with clasp.  Here is the error message:
```
Starting Boehm cclasp 0.4.0 ... loading image... it takes a few seconds
Top level.
>
;;; Loading #P"/home/jdn/work/CLang/lisp/site/pkg/slime/swank-loader.lisp"
Writing fasl file to: #P"/home/jdn/.slime/fasl/2015-11-18/clasp-cclasp-boehm-0.4.0-a1d32b6-linux-x86-64/packages.fasl"
Linking #P"/home/jdn/.slime/fasl/2015-11-18/clasp-cclasp-boehm-0.4.0-a1d32b6-linux-x86-64/packages.bc"
Linking app-contents:execs;boehm;release;bin;intrinsics_bitcode.sbc
Generating object file  /home/jdn/.slime/fasl/2015-11-18/clasp-cclasp-boehm-0.4.0-a1d32b6-linux-x86-64/packages.lbc  -->  /home/jdn/.slime/fasl/2015-11-18/clasp-cclasp-boehm-0.4.0-a1d32b6-li\
nux-x86-64/packages.o  reloc-model: RELOC-MODEL-PIC-
;../../src/core/lisp.cc:1738 execvp returned with errno=2   strerror(errno) = No such file or directory
    arg#0  clang
    arg#1  /home/jdn/.slime/fasl/2015-11-18/clasp-cclasp-boehm-0.4.0-a1d32b6-linux-x86-64/packages.o
    arg#2  -shared
    arg#3  -o
    arg#4  /home/jdn/.slime/fasl/2015-11-18/clasp-cclasp-boehm-0.4.0-a1d32b6-linux-x86-64/packages.fasl
  cannot continue... exiting... sorry...
;
;; Error while compiling /home/jdn/work/CLang/lisp/site/pkg/slime/packages.lisp:
;;   In file_truename ../../src/core/unixfsys.cc line 490
;; COMMON-LISP:FILE-ERROR :initializers (:PATHNAME "/home/jdn/.slime/fasl/2015-11-18/clasp-cclasp-boehm-0.4.0-a1d32b6-linux-x86-64/packages.fasl"  )
;;
;; Aborting.
;;

Condition of type: SIMPLE-CONTROL-ERROR
Restart ABORT is not active.
Available restarts:
(use :r1 to invoke restart 1)

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

Broken at frame[147] TOP-LEVEL.
 File: #P"/usr/local/clasp/Contents/Resources/lisp/kernel/lsp/top.lsp" (Position #21029)
```
I'd try to be more helpful and dig into this but slime is my point of entry.  I'm running Debian stable on a x86-64 machine with a very recent git pull of slime (last commit was 4 days ago).

Thanks,
Jason

**Comment by drmeister** [comment]
Clasp can't find the clang executable, it needs to be in your PATH.

**Comment by drjdn** [comment]
That never occurred to me as when building it looked like llvm-config-3.6 detected everything required.  Making a soft link to clang-3.6 and clang++-3.6 got slime to build.  It took a while to build the first time but it still isn't working.  The REPL freezes when connecting to swank.

**Comment by Shinmera** [comment]
Is there anything on the *inferior-lisp* buffer? What happens if you press C-g once it freezes? How long have you waited for it to unfreeze?

**Comment by drjdn** [comment]
OK, sorry false alarm.  It takes about ~40 or so seconds to finally connect so I was killing it too early!  I'm used to slime loading up in much less time so I was assuming it was hard frozen, apologies for the noise.

**Comment by Shinmera** [comment]
Right, unfortunately Clasp is still pretty damn slow. Please wait warmly for progress.

**Comment by Shinmera** [comment]
@drmeister Still, the problem with `clang` vs `clang-3.6`/`clang++-3.6` should be fixed. I'll leave the ticket open for that.

**Comment by drmeister** [comment]
How can I fix this problem?   The word "clang" is hardcoded into Clasp and I don't know how to figure out what the true name of the clang executable is.   "clang" is called to invoke "ld", the linker - maybe I don't even need to use clang anymore - I think I used to do that to link in bitcode files but that is now done internally and it should only be linking object files.    I'm going to change "clang" to "ld" and see if that works on OS X and Linux.  If it does then the problem should be solved once and for all.

**Comment by drmeister** [comment]
Hmm, I'm already using "ld" on OS X.   But linux requires the linking be done by clang.   How do I figure out what the name of the clang executable is on systems like drjdn's?  Should I search the PATH and look for "clang" and "clang-3.6".  Or hardcode the path `llvm-config --bindir` into clasp and look for those executables there?

**Comment by Shinmera** [comment]
Your last suggestion doesn't work due to potential deployment conflicts. My suggestion would be this: a `*clang-bin*` variable that is automatically configured at clasp bootup to look for `clang-3.6`, `clang++-3.6`, `clang`, or `clang++` on `PATH`. If it fails to find it, it is simply set to `NIL`. When the user actually needs this path in order to link something and it isn't set, they get a restart that allows them to specify the clang executable manually, which then sets the `*clang-bin*` variable.

Additionally, it would be good if `clang-3.6` and `clang++-3.6` (as in, the version numbers) were not hard-coded, but rather automatically detected through the build system so that a switch to 3.7 or sometime 3.8 won't need even more places to adapt.

**Comment by Shinmera** [comment]
See <http://plaster.tymoon.eu/view/DZ> for my suggested way of achieving most of this.

**Comment by drmeister** [comment]
Shinmera, your suggested code has been incorporated into clasp/src/lisp/kernel/cmp/external-clang.lsp with a few changes.  Everything appears to be working now.   core:*clang-bin* contains the path to the clang executable.
