### ISSUE TITLE
Building Clasp on OS X with Homebrew

### ISSUE THREAD

**Issue by GOFAI** [drmeister/clasp#180]
I've managed to successfully build clasp on OSX using the llvm-3.6 formula and its associated clang (available in the homebrew/versions tap) instead of XCode or externals-clasp. This suggests that it should now be pretty straightforward to put together a homebrew formula for clasp, but I think there may need to be some adjustments to the build system to make it meet the standards in homebrew's [Acceptable Formulae document](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md).

In case you're curious, here was my procedure:
```
brew tap homebrew/dupes
brew tap homebrew/versions
brew install llvm-3.6
brew install boost
brew install automake
brew install autoconf
brew install libtool
brew install pkg-config
brew install expat
brew install zlib
brew install readline
brew install --c++11 gmp
```
I then modified the makefile ([gist here](https://gist.github.com/GOFAI/62d99d478032ecbbbc60)) to tell it to use clang-3.6 and clang++-3.6, as well as to look for the other dependencies where homebrew installed them.

**Comment by Shinmera** [comment]
Hmm, interesting. I remember trying to use the MacPorts version of clang at some point to build Clasp and was getting strange errors about that. I'll see if I can reproduce your approach, thanks a lot for taking the time to try it out!

**Comment by drmeister** [comment]
GOFAI,  Thank you for doing this.  This is great.   I'll figure out the makefile changes.

**Comment by wuxianliang** [comment]
Any progress on this issue? This would make more people to try Clasp immediately. Thank you.

**Comment by Shinmera** [comment]
Due to the requirement of a very recent XCode and externals-clasp again, I think this'll have to wait for another time.
