### ISSUE TITLE
IN-PACKAGE returns no value instead of package

### ISSUE THREAD

**Issue by GOFAI** [drmeister/clasp#183]
``` lisp
CL-USER> (ql:quickload :iterate)
To load "iterate":
  Load 1 ASDF system:
    iterate
; Loading "iterate"

(:ITERATE)
CL-USER> (in-package :iterate)
; No value
```

Whereas in sbcl:

``` lisp
CL-USER> (in-package :iterate)
#<PACKAGE "ITERATE">
```

**Comment by drmeister** [comment]
GOFAI - thanks for these!   I'll get to them soon.   We are working on cleaning up the code for a little while.

**Comment by Shinmera** [comment]
Can confirm on b8c6690535bdc61bfdaeb50dbe23cd89633200a5
```
> (in-package #:cl)

COMMON-LISP> 
```

**Comment by Shinmera** [comment]
Returns NIL on 99669d674a6f2b7ce0a9127cf6537fc03066baa5, so still not quite right.

**Comment by Bike** [comment]
The easy fix would be to define in-package like so

    (defmacro in-package (name)
      `(eval-when (:compile-toplevel :load-toplevel :execute)
         (si::select-package ,(string name))
         (find-package ,(string name))))
