### ISSUE TITLE
Reduce Consing in Generic Function Calls

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#186]
The challenge is to reduce the consing in generic function dispatch and everything has to work properly and together in order to test it.  This diff is a work in progress and so it doesn't run but might give me an idea of what is involved in reducing consing in generic function dispatch.

Output of `diff --git a/src/lisp/kernel/clos/combin.lsp b/src/lisp/kernel/clos/combin.lsp`: [combin.lsp.diff](https://github.com/drmeister/clasp/files/46416/combin.lsp.diff.txt)

**Comment by Shinmera** [comment]
That's nice. What exactly is this issue about?

**Comment by drmeister** [comment]
I filled in the description above

**Comment by drmeister** [comment]
This is the same as issue #234
