### ISSUE TITLE
clasp 0.4 git clone fails since references to git://common-lisp.net/...git not updated

### ISSUE THREAD

**Issue by kpoeck** [drmeister/clasp#188]
Seems that one has to put 
url=https://gitlab.common-lisp.net/....git instead

**Comment by Shinmera** [comment]
Thanks for submitting this. We'll see about a 0.4.1 to fix it.

**Comment by Shinmera** [comment]
I think at this point it's better to focus on a 0.5 release.

**Comment by kpoeck** [comment]
Kind of sad to have a bug closed after nearly one year without any fix. I wonder how others checkout the code, at least for me it is not possible. Release 0.5 doesn't seem to exist yet

**Comment by Shinmera** [comment]
We've been nearing a release for some time now and 0.4 is way too far behind anything to consider continuing supporting it.
