### ISSUE TITLE
Opensuse 13.1 64bit build problems

### ISSUE THREAD

**Issue by lucashpandolfo** [drmeister/clasp#19]
# The problem #
externals-clasp built successfully, then clasp failed to link some libraries (namely cord, expat, gc, gmp, readline and history (everything minus libz)).

# The reason #
All the libs were present but in different locations. libz was at common/lib, the rest at common/lib64.

# The easy fix (almost) #
Copy (or move) all the libs from common/lib64 to common/lib and retry make.

# The fix (almost) #
Specify --libdir for each library -> http://pastebin.com/uXGpnwMu (search for --libdir)

# ~~The other problem~~ (fixed by #24 ) #
With the given fix clasp almost builds and links except for libgmp. See the log -> http://pastebin.com/kFkDwNrw. I can confirm that libgmpxx.so.4 exists  and points to the right place. A simple `LD_LIBRARY_PATH=~/clasp/externals-clasp/common/lib make` did the trick. No clue on this one (have not read the build scripts).

# The result #
A happy clasp build.

# The side note #
Lowered the number of jobs to avert memory trashing.

**Comment by Shinmera** [comment]
Needs to be reevaluated as per #135
