### ISSUE TITLE
Confusing and under-documented branch structure

### ISSUE THREAD

**Issue by Georgiy-Tugai** [drmeister/clasp#191]
**EDIT:** I'm sorry, my local view of the repository was outdated as concerns deleted branches. For future reference, to delete local remote-tracking branches (`origin/foo`) which were deleted on the remote, use `git remote prune origin`.

Clasp has a lot of branches, many of which are outdated, and almost no documentation on which branch is intended for which purpose. A particularly egregious example is `dev37` and `dev_37` -- both are purportedly intended for development towards LLVM 3.7 support; however, the former seems to be based on v0.3 and the latter on v0.4.

Branch list at the time of issue creation, annotated with descriptions to the best of my knowledge:

branch | latest commit | branch description
-------|---------------|-------------------
[`dev`]          (/drmeister/clasp/tree/dev)          | [s/ecl/clasp/ in clasp_Copyright]                     (/drmeister/clasp/commit/f04958b93392c7f1e8b1473afce741dabf7c98b3) | development head
[`dev-delete`]   (/drmeister/clasp/tree/dev-delete)   | [removed a bunch of useless files]                    (/drmeister/clasp/commit/7f37c8d47a2d4b6b3ee105b16487605729823efa) | feature
[`dev-makefile`] (/drmeister/clasp/tree/dev-makefile) | [Add cclasp-boehm-addons alias]                       (/drmeister/clasp/commit/ecf482b88675ef4d19fce87eb42fa4b7166cef67) | feature
[`dev-meister`]  (/drmeister/clasp/tree/dev-meister)  | [pulled from remote]                                  (/drmeister/clasp/commit/58116a61169c32254d9c74f7ec23dc83e94c6c56) | feature
[`dev-policy`]   (/drmeister/clasp/tree/dev-policy)   | [updated clasp_gc.cc]                                 (/drmeister/clasp/commit/0a87fd942857d0db9eebfa16d485c9957885412a) | feature
[`dev37`]        (/drmeister/clasp/tree/dev37)        | [got building with llvm37]                            (/drmeister/clasp/commit/30c4e740fda5cdccc820db36545794fd11e72f24) | major feature (LLVM 3.7 support)
[`dev_37`]       (/drmeister/clasp/tree/dev_37)       | [fixed collisions]                                    (/drmeister/clasp/commit/4d6c15764e04d621a4276b4d691d72b381159c06) | major feature (LLVM 3.7 support)
[`master`]       (/drmeister/clasp/tree/master)       | [Update README.md]                                    (/drmeister/clasp/commit/a1d32b60228a1d5395529734a299bf745b04e9ab) | release
[`mps-dev`]      (/drmeister/clasp/tree/mps-dev)      | [removed unused symbol]                               (/drmeister/clasp/commit/32471fb7a07ef55662fb84dd887b0b26c7374d2f) | 
[`preview`]      (/drmeister/clasp/tree/preview)      | [overwrote clang-tool.lsp with one from dev]          (/drmeister/clasp/commit/cd1ec7faf7024f5d32c9560ed349f5992fba540b) | pre-release
[`testing`]      (/drmeister/clasp/tree/testing)      | [Added source: and include: hostnames #182]           (/drmeister/clasp/commit/86cc38243328abc0b66b8fd98fd7d43de1d2ba5c) | continuous integration
[`testing_37`]   (/drmeister/clasp/tree/testing_37)   | [merged with remote]                                  (/drmeister/clasp/commit/3510775547363372fcf99d2f777c1cd2956b2336) | LLVM 3.7 continuous integration

**Comment by Shinmera** [comment]
Suggested branching scheme:

`->` merge into
`-<` branch into

Mainline: `dev -> testing -> preview -> master`
Sideline: `dev -< dev-* -> testing-* -> dev`
Feature:  `dev -< * -> dev`
Hotfix: `* -> testing-* -> master -> dev`

Mainline is for the primary development line on which most bugs and tickets are resolved.
Sideline is for major platform changes that would break the entire build for long times, such as for moving to the next LLVM version.
Feature lines are for individual features and tickets that get put into extra branches to make collaboration easier and cleaner.

This is mostly what [GitFlow](http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/) already describes, if I understand it correctly. There's some additions with testing branches, which allow us to make use of Autobuild for direct build and test feedback.

**Comment by rptb1** [comment]
GitFlow looks like a sensible variation on my [PQTCM](http://www.ravenbrook.com/doc/1999/05/20/pqtcm/) with command support.  I certainly suggest adopting some kind of structure, and one with command support is great.  Can I also suggest moderately strict linking of branches to issues?  If commits and branches are linked to issues there will be some hope of finding out *why* things were done as well as *what* was done.

**Comment by Shinmera** [comment]
@drmeister has begun linking to issues in commits, so that part is getting better at least.

**Comment by Shinmera** [comment]
See [CONTRIBUTING.md](https://github.com/drmeister/clasp/blob/dev/CONTRIBUTING.md) for the current mandated way of doing things.
