### ISSUE TITLE
Clasp is crashing on Linux when given unknown functions

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#193]
It's segfaulting.

It looks like the error was initiating another error from ext:compiled-function-file when the filetype of the function source info was not a lisp or c++ file.

I removed the error and now ext:compiled-function-file fails silently returning (values nil 0)

**Comment by drmeister** [comment]
Sorry, I keep forgetting to annotate these with bugs.   So many things to do.

I pushed a fix so that ext:compiled-function-file doesn't go into an infinite loop of errors when its argument isn't a function.
Fix in latest commit 8af9d9550254a413007867ecc153b5b8fc684244

**Comment by Shinmera** [comment]
I don't know if I'm testing this right (please confirm), but on b8c6690535bdc61bfdaeb50dbe23cd89633200a5
```
> (compile NIL '(lambda () (argh)))
;;; Warning: Condition: Undefined function named COMMON-LISP-USER::ARGH

#<FUNCTION/CompiledClosure LAMBDA lambda-list: COMMON-LISP:NIL>
> (funcall *)

Condition of type: SIMPLE-PROGRAM-ERROR
The symbol ARGH has no function bound to it
```

**Comment by Shinmera** [comment]
Seems fixed from what I can tell. Given no further instructions I can't test this any further than that. Reopen it if I'm wrong.
