### ISSUE TITLE
jackdaniel reports a bug in MOP

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#233]
https://gitlab.com/embeddable-common-lisp/ecl/issues/203

**Comment by Bike** [comment]
Can't reproduce in b83afab. That is, I get a list of the A method followed by the B method, which I believe is correct.

**Comment by kpoeck** [comment]
Seems to work correct, please close

#<COMMON-LISP-USER>
COMMON-LISP-USER> (defclass a () ())

#<The STANDARD-CLASS COMMON-LISP-USER::A>
COMMON-LISP-USER> (defclass b () ())

#<The STANDARD-CLASS COMMON-LISP-USER::B>
COMMON-LISP-USER> (defclass c (a b) ())

#<The STANDARD-CLASS COMMON-LISP-USER::C>
COMMON-LISP-USER> (defmethod f ((o a)))

#<STANDARD-METHOD F (A)>
COMMON-LISP-USER> (defmethod f ((o b)))

#<STANDARD-METHOD F (B)>
COMMON-LISP-USER> (clos:compute-applicable-methods-using-classes #'f (list (find-class 'c)))

(#<STANDARD-METHOD F (A)> #<STANDARD-METHOD F (B)>)
