### ISSUE TITLE
Eliminate special variables from generic function dispatch

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#234]
The "testgf" branch contains the code that stassats and I worked on to eliminate special variables being used to store combined-method-args and next-methods from generic-function dispatch.

It was able to successfully compile cclasp - but ran into trouble with ASDF.

It reduces the amount of memory consed when compiling cclasp by 1/2 to 2/3rd

**Comment by drmeister** [comment]
I think we have this finished - Stas and I made a lot of changes to the CLOS to eliminate special variables and I've been using it for a couple of weeks with no problems.   I'm about to share the code with jackdaniel and he will incorporate it into ECL and test it more thoroughly

**Comment by Shinmera** [comment]
Is there anything I can do to confirm this, other than checking that Clasp is just running?

**Comment by drmeister** [comment]
jackdaniel is backporting these changes to ECL and he will run a test suite on it there.

**Comment by Shinmera** [comment]
Closing as I think this is done,  but there's no real way to test.
