### ISSUE TITLE
Timing of builds on my Linux and OS X machines

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#236]
commit 0a4a715c243d2989978803bbcbc692ee02e0b8bb
Author: Chris Schafmeister <chris.schaf@verizon.net>
Date:   Mon Apr 18 02:50:44 2016 -0400

    working on speeding up gf dispatch
Linux:
real    222m5.866s
user    240m13.639s
sys     16m56.195s

OS X: 261 min

**Comment by drmeister** [comment]
commit bf16ee0af5d20f1f37bed752f9097806010f0195
Author: drmeister <chris.schaf@verizon.net>
Date:   Mon Apr 18 08:27:51 2016 -0400

    Added USE_EXPENSIVE_BACKTRACE define

Linux: 
real    200m28.460s
user    222m39.397s
sys     5m27.810s

**Comment by drmeister** [comment]
commit c830fe26aac7a3624a6ea1f9d11a9dd262a3b454
Merge: 0bcf685 6e33bb7
Author: drmeister <chris.schaf@verizon.net>
Date:   Mon Apr 18 22:35:01 2016 -0400

    merged with remote

Linux:
real    154m36.599s
user    174m15.268s
sys     15m29.289s

**Comment by drmeister** [comment]
commit 891720b74c1a6eef15296fc32cd42bbf81bddfc8
Merge: 1517c1f fdb414d
Author: Chris Schafmeister <chris.schaf@verizon.net>
Date:   Tue Apr 19 01:34:10 2016 -0400

    merged with remote

Linux:
real    161m55.367s
user    182m2.108s
sys     17m48.124s

**Comment by drmeister** [comment]
commit a5e8f991a2999530c62332b66e4b59895c723371
Author: drmeister <chris.schaf@verizon.net>
Date:   Tue Apr 19 08:29:30 2016 -0400

    Added recompile-cclasp function to init.lsp

    For recompiling cclasp when changes are made to source.

real    169m20.935s
user    187m22.836s
sys     18m10.777s

**Comment by drmeister** [comment]
Hmmm, making aref use &va-rest didn't buy anything.

commit d4ff3945239d86742721ab184c1c812c2de046d3
Author: drmeister <chris.schaf@verizon.net>
Date:   Tue Apr 19 12:47:53 2016 -0400

    Restored ASET

real    171m55.129s
user    190m39.867s
sys     17m14.894s

**Comment by drmeister** [comment]
commit 9e05976c3f129532d03117a38c6b734249934ca5
Merge: fa53587 33462a2
Author: drmeister <chris.schaf@verizon.net>
Date:   Thu Apr 21 14:44:23 2016 -0400

    Merge branch 'dev'

    of https://github.com/drmeister/clasp into dev

real    154m57.465s
user    178m48.668s
sys     23m32.600s

**Comment by drmeister** [comment]
commit a51a6413674b95e7f1e9aa02e868a146a6514c82
Author: drmeister <chris.schaf@verizon.net>
Date:   Sat Apr 23 17:37:18 2016 -0400

    Fixed problems with backtraces

    I had to reset va_list's

real    147m13.865s
user    169m41.280s
sys     27m30.975s

**Comment by drmeister** [comment]
Commit de711c42bce91e0ee5f4771500fc665167b0971a

real    122m53.485s
user    147m28.790s
sys     25m2.922s

**Comment by drmeister** [comment]
I'm not sure that last data point was valid - the builds are back up at 150 min
commit 5f6c89bcd471e66873b163f019f56811b54173e8
Author: Chris Schafmeister <chris.schaf@verizon.net>
Date:   Mon Apr 25 12:41:35 2016 -0400

    Made clasp-backtrace use *stack-top-hint

real    151m56.389s
user    176m12.189s
sys     19m35.310s

**Comment by Shinmera** [comment]
Should probably be a wiki entry instead, or a simple paste file instead of an issue.
