### ISSUE TITLE
(compile nil '(print 10)) should signal an error

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#237]

**Comment by Shinmera** [comment]
Still there on 99669d674a6f2b7ce0a9127cf6537fc03066baa5

**Comment by Bike** [comment]
This could be an assert in compile*'s definition: `((consp definition) (assert (eq (first definition) 'lambda) ...) ...)`

Could also be put lower down (e.g. asserting some AST is a FUNCTION-AST), but that should be fine if clasp doesn't have more kinds of function names.
