### ISSUE TITLE
(function-lambda-list 'make-instance) --> 0  

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#242]
It should return a lambda list.
I think the problem may be how I augment generic function lambda lists.

**Comment by drmeister** [comment]
I think this is fixed.
```> (function-lambda-list 'make-instance)

(CLASS &REST CLOS::INITARGS)
T
```

**Comment by Shinmera** [comment]
Confirm fixed on 99669d674a6f2b7ce0a9127cf6537fc03066baa5
