### ISSUE TITLE
Subclass[COMMON-LISP:BIGNUM] must implement method[negate_] 

### ISSUE THREAD

**Issue by kpoeck** [drmeister/clasp#246]
(lisp-implementation-version)
"cclasp-boehm-0.4.0-2-g6b956b1"
(- (/ 6510824913153389230080000000 2108726800736564736000000000))
->
Condition of type: SIMPLE-PROGRAM-ERROR
File(../../include/clasp/core/numbers.h) lineNumber(197): Subclass[COMMON-LISP:BIGNUM] must implement method[negate_] 

Available restarts:
(use :r1 to invoke restart 1)
1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

**Comment by Shinmera** [comment]
Can confirm on e6bb007e1e08efd009471cff666436c95945c69d

**Comment by Bike** [comment]
Can't reproduce on 35f15d4. It's -281781717/912652650.
