### ISSUE TITLE
Consp Appears to Not Be Inlined in Every Case

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#253]
I thought Cleavir inlining was universally applied in cclasp - maybe not.
Trap the cl__consp function with the debugger and find out where it isn't inlined.

**Comment by Shinmera** [comment]
How do I test this?

**Comment by Bike** [comment]
I'm going to close this and #251 as too vague, and because things have changed a lot since last September, and because we're right in the middle of redoing type checks entirely and Cleavir is going to have new inlining and yada yada yada.
