### ISSUE TITLE
Common Lisp source dependencies need to be provided to waf wscript file

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#264]
Currently the waf build system doesn't know anything about what Common Lisp source files are dependencies of the different Xclasp-boehm-common-lisp.bc files for each stage X.
This screws up incremental building of the Common Lisp code.

**Comment by Shinmera** [comment]
How do you have the dependencies noted now? Are they in ASDF systems or just not noted down anywhere at all?

**Comment by michaelleerilee** [comment]
I trying to bring up clasp testing on Fedora 24 and I think I'm running into this. The build is failing, not finding "aclasp-boehm-common-lisp.bc".

**Comment by drmeister** [comment]
This is fixed now.  The waf build system knows everything about the order of Common Lisp file compilation.  It's stored in clasp/src/lisp/kernel/build_files.py and  cleavir.py  in that directory.
