### ISSUE TITLE
(core:function-lambda-list 'clos:generic-function-methods)  -> 0

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#271]
It returns zero (0) - it should return a lambda list.
Clasp does support:

> > (clos:generic-function-lambda-list #'clos:generic-function-methods)
> > (CLOS::SELF)

But stassats says that this returns NIL, T for user defined accessors.

**Comment by Bike** [comment]
Can't reproduce on 35f15d4; it returns (CORE::OBJECT), T.
