### ISSUE TITLE
undefined-function: base-string-p

### ISSUE THREAD

**Issue by dkochmanski** [drmeister/clasp#287]
Clasp uses `base-string-p` function in `seqlib.lsp` and `predlib.lsp`, but it doesn't define it anywhere. This is copied from ECL, but ECL defines it in the compiler package:

```
src/cmp/sysfun.lsp:564:(def-inline base-string-p :always (t) :bool "@0;ECL_BASE_STRINGP(#0)")
src/cmp/proclamations.lsp:889:(proclamation si:base-string-p (t) gen-bool :pure)
```

while Clasp doesn't define it anywhere

**Comment by drmeister** [comment]
base-string-p has been added for a while.
