### ISSUE TITLE
Read-sequence return-value incorrect

### ISSUE THREAD

**Issue by pipping** [drmeister/clasp#294]
```common-lisp
(let ((buffer (make-array '(8192) :element-type 'character)))
  (with-input-from-string (in "foo")
    (read-sequence buffer in)))
```
should return `3` but returns `8192`.

Sidenote: As a consequence, this means that
```common-lisp
(with-input-from-string (in "foo")
  (with-output-to-string (out)
    (uiop:copy-stream-to-stream in out)))
```
will continue to allocate memory until you run out of it because it does so until `read-sequence` returns `0` (which it never does here). Code like the above is part of e.g. UIOP's `run-program` implementation when the output is to a string.

**Comment by pipping** [comment]
Another test case for this is provided in the CLHS at http://clhs.lisp.se/Body/f_rd_seq.htm

Expected:
```
 (defvar *data* (make-array 15 :initial-element nil))
 (values (read-sequence *data* (make-string-input-stream "test string")) *data*)
 =>  11, #(#\t #\e #\s #\t #\Space #\s #\t #\r #\i #\n #\g NIL NIL NIL NIL)
```
Actual:
```
(defvar *data* (make-array 15 :initial-element nil))
(values (read-sequence *data* (make-string-input-stream "test string")) *data*)
=> 15
Segmentation fault (core dumped)
```

**Comment by drmeister** [comment]
I found the source of this bug and fixed it. I'll push with a few other changes soon.

**Comment by pipping** [comment]
All the failing examples contained in this bug report now work.
