### ISSUE TITLE
Various Objects Can't Be Dumped to FASL

### ISSUE THREAD

**Issue by Shinmera** [drmeister/clasp#296]
Clasp currently does not support dumping a variety of objects to FASLs, including very basic things like ratios, random-state, and the general `make-load-form`.

See [src/lisp/kernel/cmp/cmpquote.lsp#L900](https://github.com/drmeister/clasp/blob/c2af9df02b1755390788d8a1d4f1953d6812f59a/src/lisp/kernel/cmp/cmpquote.lsp#L900).

**Comment by drmeister** [comment]
Ratio's are now written to fasls.   RANDOM-STATE's are not written yet.
I also haven't addressed the make-load-form issue

**Comment by Bike** [comment]
make-load-form is in from drmeister's commits starting around c8689e8. I think random states are still broken.

**Comment by Shinmera** [comment]
Random-states should be fixed by 2a58cb357a8f3b35a131f2cb1e4696e3db50d897, will confirm as soon as it's done compiling.

**Comment by Shinmera** [comment]
I can dump random-states to fasls indeed, but the way they are dumped and read back in is not correct, or something else is not correct. Either way-- test case:

test.lisp:
```common-lisp
(defmacro foo ()
  (make-random-state))

(defun bar ()
  (random 100 (foo)))
```

Tested with:
```shell
clasp --load test.lisp --eval "(print (bar))" -N
```

Expected to get the same number printed every launch, but it instead generates different numbers each run, indicating that either a new random-state is generated every time `bar` is called, or that `random` does not respect the state argument.

**Comment by Shinmera** [comment]
Actually there's something really fukin' weird going on that I don't understand.

**Comment by drmeister** [comment]
I changed the behavior of clasp so that the first *random-state* that is initialized - is now initialized with the same seed.  This means that when Clasp starts up it will generate the same sequence of random numbers every time.  This is in commit:  76c2c18

**Comment by attila-lendvai** [comment]
is this a good idea?

i'd expect a system to have the best random seed it can provide by default, and reproducible random seeds to be used only when explicitly requested.

**Comment by Shinmera** [comment]
The spec says that the initial value of `*random-state*` is implementation-dependant. If you want to be sure that it's fresh, you need to do that yourself anyway.

Plus, having a new seed every startup would potentially make it impossible to reproduce problems that occur due to reliance on random number generation.

**Comment by attila-lendvai** [comment]
...for programs whose output depends on the random seed, and that lack a reasonable test suite. that seems to be precious little on the pro side for this change.

it's not super important, but certainly not what i'd expect.

**Comment by Shinmera** [comment]
Both SBCL and CCL also don't seed the state on startup, so I'd say it is what people would expect just based on what the most popular implementations do.

**Comment by Bike** [comment]
Why is this open? random states, ratios, and instances with m-l-f seem to dump fine now.

**Comment by drmeister** [comment]
This should all work now.
