### ISSUE TITLE
Change calling convention again - use more registers - pass rest in multiple_values array!

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#3]
pkhuong in #sbcl suggested passing remaining arguments in the multiple_values array.
He also suggested setting up the lambda-list processing code so that it first processes all of the provided argument and then in a second pass processes the default/initial forms.
He said I can keep track of which arguments are missing in scalar registers.

**Comment by Shinmera** [comment]
Outdated and irrelevant.
