### ISSUE TITLE
MAKE-SEQUENCE Does Not Accept Class of Fill-Pointer Vectors

### ISSUE THREAD

**Issue by Shinmera** [drmeister/clasp#303]
A vector with a fill-pointer returns an unreadable class instance:

```
> (class-of (make-array 5 :fill-pointer T :initial-element 1))

#<BUILT-IN-CLASS VECTOR-OBJECTS-WITH-FILL-PTR>
```

This in turn is not appreciated by `make-sequence`:

```
> (make-sequence * 5)

Condition of type: SIMPLE-TYPE-ERROR
#<BUILT-IN-CLASS VECTOR-OBJECTS-WITH-FILL-PTR> does not specify a sequence type
```

This also affects functions such as `map` which call `make-sequence` internally.

**Comment by Bike** [comment]
the error is signalled from closest-sequence-type. That function looks kind of jacked itself, but notably `(subtypep that-class 'vector) => NIL, T` and `(subtypep that-class (find-class 'vector)) => T, T` which is very wrong.

**Comment by Shinmera** [comment]
Can confirm still existing on dcc6f10e04e998f628a90922797eeca6dd8b68f9

**Comment by Bike** [comment]
On b83afab (post array rewrite) there is no error signaled, but the result of make-sequence does not have a fill pointer. I don't know if that conforms.

**Comment by Shinmera** [comment]
I'm pretty sure that is Ok, as the fill-pointer is not expressible in an array type.

**Comment by Bike** [comment]
Yeah, CLHS says it needs length and UAET, and only the latter is potentially involved here, so I think we're good.
