### ISSUE TITLE
Bringing SLIME to Clasp

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#31]
I would really, really love to have SLIME integration with Clasp.  I've wanted it since I first discovered SLIME and Clasp was just a crazy glimmer in my lazy eye.  I've put some work into enabling SLIME support but I haven't yet done any actual work with SWANK (the part of SLIME that would run within Clasp).

Here's what is already incorporated into Clasp to support SLIME/SWANK.

- I've incorporated Gray streams within Clasp - they seem to work mostly.

- I've exposed sockets functions and the code for them is in the clasp/src/sockets directory and in the #:SB-BSD-SOCKETS and #:SOCKETS-INTERNAL packages in Clasp.

- I've exposed some SERVE-EVENT functions and they are in the clasp/src/serveEvent directory and in the #:SERVE-EVENT-INTERNAL package in Clasp.

- A couple of months ago I managed to get everything working well enough to open a telnet session with a programming running in Clasp and send forms to it and receive results.

That's as far as I got before I got distracted with getting the static analyzer and MPS integration working and releasing Clasp.

Note: Clasp is very similar to ECL internally. So the ECL SWANK code could be used as a starting point to write the Clasp SWANK code. I use all of the non-compiler parts of the ECL Common Lisp source code. I mimic a lot of the C functionality in ECL with C++ functionality in Clasp.  Any differences between the CLHS and Clasp are bugs in Clasp.  Any differences between how the exposed functions in Clasp and the exposed functions in ECL behave can be changed to make them behave more like ECL if it retains compatibility with the CLHS and makes it easier to get external code (like SWANK) to work with Clasp.

If anyone wants to pick this up where I left off I'm happy to provide assistance.  I wouldn't be able to make any serious progress on SLIME integration before the new year.  But if you have time and want to step up and participate - all accolades and praise will go to you!

**Comment by Shinmera** [comment]
Slime is working with Clasp as much as possible for the moment. Further steps might have to be involved once Clasp gets threading support and similar extensions.

**Comment by jgarte** [comment]
Hi,

Has anyone tested Sly with Clasp in 2024?

**Comment by yitzchak** [comment]
@jgarte This PR has been closed for 9 years. You should ask that question elsewhere. And yes we use SLIME with clasp in 2024.
