### ISSUE TITLE
Update the license files

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#312]
https://github.com/drmeister/clasp/blob/master/licenses/ecl_Copyright#L24 https://github.com/drmeister/clasp/blob/master/licenses/clasp_Copyright#L32 

Shinmera said:
1) update the paths 
2) include verbatim copies of the actual license texts as a file
So the LGPL2.1+ for ECL and.. whatever you picked for Clasp.
If both are the same then you can include that file as LICENSE in Clasp's root.

**Comment by drmeister** [comment]
1. update the paths
Question:  Specifically, which paths?
2. include verbatim copies of the actual license texts as a file...
Could you provide a link for the LGPL2.1 that I can copy?  I'll choose the LGPL2.1 for Clasp.

**Comment by Shinmera** [comment]
Marked at the lines that are linked in the OP are paths that refer to directories in the source tree. I have no idea if these paths are still accurate by now given that the file has never been updated.

If you use the same as ECL's, then you can just copy ECL's: https://gitlab.com/embeddable-common-lisp/ecl/raw/develop/COPYING

**Comment by Shinmera** [comment]
Seems fine now. Thanks.
