### ISSUE TITLE
Slime Inspector: Inspecting a list results in error "The symbol COMMON-LISP:FUNCTION-LAMBDA-EXPRESSION has no function bound to it"

### ISSUE THREAD

**Issue by dg1sbg** [drmeister/clasp#318]
When in an Slime inspector buffer and displaying a CONS the error is popping up as soon as RETURN is pressed on the first element of the list shown as "A proper list". See attached screen dump.
[sd-clasp-slime-error.pdf](https://github.com/drmeister/clasp/files/629756/sd-clasp-slime-error.pdf)

**Comment by Bike** [comment]
I believe the problem wasn't the list, but inspecting a function. Something in the slime inspector probably calls FUNCTION-LAMBDA-EXPRESSION for that.

And FUNCTION-LAMBDA-EXPRESSION wasn't defined. I defined it in fb7c1ff. I can now inspect e.g. (list #'+ #'-) without any problem.
