### ISSUE TITLE
Ubuntu Installation Guide 

### ISSUE THREAD

**Issue by JacobGood1** [drmeister/clasp#33]
Guide for Ubuntu 14.04

1-Before doing anything run these commands in the terminal.

sudo apt-get install m4 g++ ncurses-dev libbz2-dev libgmpxx4ldbl

export BOOST_BUILD_PATH=”/home/{computer-name}/clasp/boost_build_v2”

2-Now, go to the externals-clasp folder and make a document called local.config

3-Find the local.config.linux file, copy everything from that file and place it inside of local.config

4-Inside of local.config comment out the GCC_TOOLCHAIN

#export GCC_TOOLCHAIN = “who cares”

5-Go to your externals-clasp folder and run make

6-Finally, go to your clasp folder that you cloned from github and run make inside of it.

Happy Lisping!

**Comment by Shinmera** [comment]
Needs to be reevaluated as per #135
