### ISSUE TITLE
Debian packaging for Clasp

### ISSUE THREAD

**Issue by fmitha** [drmeister/clasp#34]
I'm working on some basic Debian packaging for Clasp. Preliminary tests suggest that Clasp is really close to buildable to Debian testing/unstable as is. There are a few relatlvely minor road bumps.
So, I'm creating this issue to track my progress.

There is some earlier discussion about this at https://github.com/drmeister/clasp/issues/22

The most relevant thing there is that the Boehm package Clasp uses is a (minor) fork of upstream, differing by a small patch. 

Current status: I've patched the Debian Boehm package with the Clasp patch. Preliminary tests suggest Clasp builds against it Ok.

Currently I'm trying to figure out how to create an `orig.tar.gz` tarball. This is complicated because the Clasp Git subrepository contains git submodules of ASDF and MPS.

**Comment by raould** [comment]
Thank you for all your hard work! Is this something that is releasable to dummies like me who are sucker enough to try it out on their own local machine? ;-)

**Comment by fmitha** [comment]
On Wed, 15 Apr 2015, Raoul Duke wrote:

> Thank you for all your hard work! Is this something that is releasable 
> to dummies like me who are sucker enough to try it out on their own 
> local machine? ;-)

Hi,

This version of the Debian packaging was for an old and probably out of 
date version of Clasp. I don't think building the packaging itself would 
be a problem, but you might want to ask Chris when he is going to be 
releasing the next version, because the packaging will need to be changed 
for that version. As you are probably aware, Clasp is still changing fast.

                                                          Regards, Faheem

**Comment by Shinmera** [comment]
Given Clasp's instability, frequent changes and updates, heavy dependencies, and general bulkiness I think it's still premature to include it in any distributions. We can reopen this once things have levelled out.
