### ISSUE TITLE
Attempting to fetch and checkout submodules fails

### ISSUE THREAD

**Issue by swflint** [drmeister/clasp#365]
$ nix-prefetch-git --fetch-submodules git://github.com/drmeister/clasp.git
    Initialized empty Git repository in /tmp/git-checkout-tmp-zdYTLErW/clasp/.git/
    remote: Counting objects: 1098, done.
    remote: Compressing objects: 100% (1005/1005), done.
    remote: Total 1098 (delta 297), reused 238 (delta 29), pack-reused 0
    Receiving objects: 100% (1098/1098), 2.55 MiB | 4.21 MiB/s, done.
    Resolving deltas: 100% (297/297), done.
    From git://github.com/drmeister/clasp
     * branch            HEAD       -> FETCH_HEAD
    Switched to a new branch 'fetchgit'
    Submodule 'src/lisp/kernel/contrib/Acclimation' (https://github.com/robert-strandh/Acclimation.git)     registered for path 'src/lisp/kernel/contrib/Acclimation'
    Submodule 'src/lisp/kernel/contrib/sicl' (https://github.com/Bike/SICL.git) registered for path     'src/lisp/kernel/contrib/sicl'
    Submodule 'src/lisp/modules/asdf' (https://gitlab.common-lisp.net/asdf/asdf.git) registered for path     'src/lisp/modules/asdf'
    Submodule 'src/mps' (https://github.com/Ravenbrook/mps.git) registered for path 'src/mps'
    Initialized empty Git repository in     /tmp/git-checkout-tmp-zdYTLErW/clasp/src/lisp/kernel/contrib/Acclimation/.git/
    remote: Counting objects: 180, done.
    remote: Total 180 (delta 0), reused 0 (delta 0), pack-reused 180
    Receiving objects: 100% (180/180), 19.81 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (109/109), done.
    From https://github.com/robert-strandh/Acclimation
     * [new branch]      master     -> origin/master
    Switched to a new branch 'fetchgit'
    Initialized empty Git repository in     /tmp/git-checkout-tmp-zdYTLErW/clasp/src/lisp/kernel/contrib/sicl/.git/
    remote: Counting objects: 72484, done.
    remote: Compressing objects: 100% (59/59), done.
    remote: Total 72484 (delta 59), reused 71 (delta 43), pack-reused 72382
    Receiving objects: 100% (72484/72484), 11.35 MiB | 3.09 MiB/s, done.
    Resolving deltas: 100% (55185/55185), done.
    From https://github.com/Bike/SICL
     * [new branch]          clasp-changes       -> origin/clasp-changes
     * [new branch]          clos                -> origin/clos
     * [new branch]          condition-signaling -> origin/condition-signaling
     * [new branch]          lambda-lists        -> origin/lambda-lists
     * [new branch]          master              -> origin/master
    fatal: reference is not a tree: 8f637326f8b1a2cec32e65e81bdb3e435e3b6dc3
    Unable to checkout 8f637326f8b1a2cec32e65e81bdb3e435e3b6dc3 from https://github.com/Bike/SICL.git.

There appears to be an issue in the declaration for the SICL submodule.  I am therefore unable to build the repository.

When I attempt to manually fetch (`git submodule update --init`) , I get the following output:

    Submodule 'src/lisp/kernel/contrib/Acclimation' (https://github.com/robert-strandh/Acclimation.git)     registered for path 'src/lisp/kernel/contrib/Acclimation'
    Submodule 'src/lisp/kernel/contrib/sicl' (https://github.com/Bike/SICL.git) registered for path     'src/lisp/kernel/contrib/sicl'
    Submodule 'src/lisp/modules/asdf' (https://gitlab.common-lisp.net/asdf/asdf.git) registered for path     'src/lisp/modules/asdf'
    Submodule 'src/mps' (https://github.com/Ravenbrook/mps.git) registered for path 'src/mps'
    Cloning into '/home/swflint/gits/clasp/src/lisp/kernel/contrib/Acclimation'...
    Cloning into '/home/swflint/gits/clasp/src/lisp/kernel/contrib/sicl'...
    Cloning into '/home/swflint/gits/clasp/src/lisp/modules/asdf'...
    Cloning into '/home/swflint/gits/clasp/src/mps'...
    Submodule path 'src/lisp/kernel/contrib/Acclimation': checked out 'dd15c86b0866fc5d8b474be0da15c58a3c04c45c'
    error: Server does not allow request for unadvertised object 8f637326f8b1a2cec32e65e81bdb3e435e3b6dc3
    Fetched in submodule path 'src/lisp/kernel/contrib/sicl', but it did not contain     8f637326f8b1a2cec32e65e81bdb3e435e3b6dc3. Direct fetching of that commit failed.

**Comment by Bike** [comment]
The SICL submodule is based on rebasing, which tends to wreak havoc and erase old commits. We mostly work in the dev branch, so I tend to update the submodule just for dev, making master impossible to use.

You are not the first person to run into this. Since the object does exist on github, I will try putting it in a branch so that it is accessible.

**Comment by swflint** [comment]
Thanks!

**Comment by Bike** [comment]
Try it now.

I am not completely clear on how submodules work with remotes, but I think the master SICL is retrievable now.

**Comment by swflint** [comment]
Well, it works!

**Comment by Bike** [comment]
Fantastic. I'll avoid breaking master with time travel shenanigans in the future.
