### ISSUE TITLE
mistake in  install instructions for 0.5 on OS X

### ISSUE THREAD

**Issue by quarkcharmer** [drmeister/clasp#380]
Mistake in step 3 or 4: step 4 tries to create symbolic links in a directory, v1, which has been removed in step 3 (renamed as v1-original)

**Comment by drmeister** [comment]
I think the instructions are correct.   The directory 'v1' is the symbolic link.

**Comment by kpoeck** [comment]
i did as instructed and the result was as advertised. I strongly believe quarkcharmer is in error here

**Comment by quarkcharmer** [comment]
my apologies for the false alarm, you're right. I mistook a line feed on the web page instructions for a space ! many thanks for checking so quickly
