### ISSUE TITLE
Subclass BIGNUM must implement method sqrt

### ISSUE THREAD

**Issue by kpoeck** [drmeister/clasp#385]
While executing ansi-tests, perhaps SQRT.16

Subclass BIGNUM must implement method sqrt_
cclasp-boehm (../../src/main/main.cc:362): The generic catch(...) caught an unhandled exception of type 0x10f672ed0 - this is a bug. Please report this to clasp support !
*** BACKTRACE:
stack trace:
  1   cclasp-boehm                        0x000000010e993f16 _ZL7startupiPPcRbRiS2_ + 2486
  2   cclasp-boehm                        0x000000010e51c4d8 _ZN7gctools32startupGarbageCollectorAndSystemEPFiiPPcRbRiS3_EiS1_mbii + 232
  3   cclasp-boehm                        0x000000010e993400 main + 848
  4   libdyld.dylib                       0x00007fff55506145 start + 1
  5   ???                                 0x0000000000000003 0x0 + 3

**Comment by stassats** [comment]
Isn't tis #306?

**Comment by Shinmera** [comment]
It is indeed.
