### ISSUE TITLE
sqrt of a fixnum should return a double (or a long?)

### ISSUE THREAD

**Issue by Bike** [drmeister/clasp#390]
Right now it's a single, and I'm not sure how the code works so I don't want to touch it.

**Comment by olopierpa** [comment]
Il giorno 8 novembre 2017, alle ore 17:01, Неточка Незванова <notifications@github.com> ha scritto:

>
>
>Right now it's a single, and I'm not sure how the code works so I don't want to touch it.

If SQRT of a rational returns a float, then the float must be a single-float.

See http://www.lispworks.com/documentation/HyperSpec/Body/12_acc.htm for the details.

**Comment by Bike** [comment]
huh. weird. i'll go fix bignums again then.
