### ISSUE TITLE
(array-rank 0) segfaults

### ISSUE THREAD

**Issue by kpoeck** [drmeister/clasp#392]
From Ansi-tests 
(deftest array-rank.error.3
  (check-type-error #'array-rank #'arrayp)
  nil)
;; Session
karsten-poecks-macbook-pro:ansi-cl-tests karstenpoeck$ ~/lisp/compiler/clasp/build/boehm/cclasp-boehm
Starting Boehm cclasp FRGO_CLASP_DEV_FOREIGN_DATA_002-1990-gc9f423501 ... loading image... it takes a few seconds
Top level in: #<PROCESS TOP-LEVEL @0x10c1d0e7f>.
COMMON-LISP-USER> (array-rank 0)
Segmentation fault: 11

**Comment by Bike** [comment]
https://github.com/drmeister/clasp/blob/dev/src/lisp/kernel/cleavir/inline.lisp#L452 should be `array` not `t`. I'll fix that. Wonder how i fucked that up.

**Comment by Bike** [comment]
@kpoeck Can you still reproduce?

**Comment by kpoeck** [comment]
COMMON-LISP-USER>  (array-rank 0)

Condition of type: CASE-FAILURE
0 fell through ETYPECASE expression.
Wanted one of ((SIMPLE-ARRAY * (*)) ARRAY).

Available restarts:
(use :r1 to invoke restart 1)

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

Broken at frame[0] NIL. In: #<PROCESS TOP-LEVEL @0x108cd8f29>.

So also fixed!
