### ISSUE TITLE
(make-random-state :a) -> unhandled exception

### ISSUE THREAD

**Issue by kpoeck** [drmeister/clasp#393]
COMMON-LISP-USER>>> (make-random-state :a)
cclasp-boehm (../../src/main/main.cc:362): The generic catch(...) caught an unhandled exception of type 0x108c3f070 - this is a bug. Please report this to clasp support !
*** BACKTRACE:
stack trace:
  1   cclasp-boehm                        0x0000000107fa2056 _ZL7startupiPPcRbRiS2_ + 2486
  2   cclasp-boehm                        0x0000000107ab5708 _ZN7gctools32startupGarbageCollectorAndSystemEPFiiPPcRbRiS3_EiS1_mbii + 232
  3   cclasp-boehm                        0x0000000107fa1540 main + 848
  4   libdyld.dylib                       0x00007fff59e84145 start + 1

**Comment by Bike** [comment]
@kpoeck Can you still reproduce?

**Comment by kpoeck** [comment]
COMMON-LISP-USER> (make-random-state :a)

Condition of type: TYPE-ERROR
:A is not of type (OR RANDOM-STATE NULL (EQL T)).

Available restarts:
(use :r1 to invoke restart 1)

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

Is fixed!
