### ISSUE TITLE
describe fails on vectors

### ISSUE THREAD

**Issue by kpoeck** [drmeister/clasp#396]
COMMON-LISP-USER> (describe #(1 2 3))

#(1 2 3) - simple vector
Condition of type: SIMPLE-PROGRAM-ERROR
The symbol CORE::INSPECT-PRINT has no function bound to it

Available restarts:
(use :r1 to invoke restart 1)

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

Broken at frame[0] NIL. In: #<PROCESS TOP-LEVEL @0x11321fe7f>.

**Comment by kpoeck** [comment]
reason seems obvious

in describe.lisp
#+clasp-min
(defmacro inspect-print (label object &optional place) 
....)

In my image clasp-min is not set

**Comment by kpoeck** [comment]
Perhaps the following is a valid fix:
```
#+(or clasp-min CCLASP)
(defmacro inspect-recursively (label object &optional place)
  (if place
      `(multiple-value-bind (update-flag new-value)
            (read-inspect-command ,label ,object t)
         (when update-flag (setf ,place new-value)))
      `(when (read-inspect-command ,label ,object t)
             (princ "Not updated.")
             (terpri))))

#+(or clasp-min CCLASP)
(defmacro inspect-print (label object &optional place)
  (if place
      `(multiple-value-bind (update-flag new-value)
           (read-inspect-command ,label ,object nil)
         (when update-flag (setf ,place new-value)))
      `(when (read-inspect-command ,label ,object nil)
             (princ "Not updated.")
             (terpri))))
```

**Comment by Bike** [comment]
`clasp-min` is set only in the early part of building. I don't know why it's conditionalized out like this; it's inherited from ecl. i'll be testing just removing the condition entirely.

**Comment by Bike** [comment]
d6a8b3a1 indeed seems to have fixed the problem.

**Comment by kpoeck** [comment]
Did fix the problem, thanks!
