### ISSUE TITLE
(elt  (make-array '(0) :adjustable t) 0) dies with Segmentation fault: 11 in cclasp-mps but not in cclasp-boehm

### ISSUE THREAD

**Issue by kpoeck** [drmeister/clasp#398]
COMMON-LISP-USER> (lisp-implementation-version)
"cclasp-mps-FRGO_CLASP_DEV_FOREIGN_DATA_002-2078-g64a7b84bb"
COMMON-LISP-USER> (elt  (make-array '(0) :adjustable t) 0)
#<VA-LIST: Segmentation fault: 11

but
COMMON-LISP-USER> (lisp-implementation-version)
"cclasp-boehm-FRGO_CLASP_DEV_FOREIGN_DATA_002-2079-g04bd2a685"
COMMON-LISP-USER> (elt  (make-array '(0) :adjustable t) 0)
0

**Comment by kpoeck** [comment]
overlaps with #395

**Comment by Bike** [comment]
Can't reproduce, but I just get NIL rather than a type error, so clearly something's screwy.

**Comment by kpoeck** [comment]
Now results in a nice simple-error, fixed, so closing
