### ISSUE TITLE
INTEGER-LENGTH is undefined

### ISSUE THREAD

**Issue by cwandrews** [drmeister/clasp#40]
The function INTEGER-LENGTH is not currently defined. It can be found in the HyperSpec [here](http://clhs.lisp.se/Body/f_intege.htm). It should return the number of bits required to represent the number that was given as a parameter, for example: 

```
> (integer-length 5)
3
```

**Comment by k--r** [comment]
seems to work for me, on tag 0.3-test-6

so maybe this issue should be closed ?
