### ISSUE TITLE
trace and fmakunbound interact poorly

### ISSUE THREAD

**Issue by Bike** [drmeister/clasp#400]
```
(defun foo ())
(trace foo)
(fmakunbound 'foo)
```

`fmakunbound` does not touch the trace record (which is lisp-level, unlike `fmakunbound` which is C++). Now `(untrace)` and `(untrace foo)` fail, complaining that `foo` is unbound. This seems to be due to `traced-and-redefined-p`, which tries to get the fdefinition.

Solution is probably for `fmakunbound` to eliminate the trace record.

**Comment by kpoeck** [comment]
Woudn't it also be possible to do the following in .../kernel/lsp/trace.lsp
```
(defun untrace-one (fname)
  (let ((record (trace-record fname)))
    (cond ((null record)
           (warn "The function ~S was not traced." fname))
           ((not (fboundp fname))
            (warn "The function ~S was traced, but fmakunbound." fname))
          ((traced-and-redefined-p record)
           (warn "The function ~S was traced, but redefined." fname))
          (t
           (sys:fset fname (trace-record-old-definition record))))
    (delete-from-trace-list fname)
    (values)))

**Comment by kpoeck** [comment]
traced-and-redefined-p calls fdefinition of the function, so it either shoudn't be called at all, or test id function is still fbound

**Comment by kpoeck** [comment]
I believe this is fixed with pr https://github.com/drmeister/clasp/pull/405

please verify

**Comment by drmeister** [comment]
I'm going to merge this and give it a try.

**Comment by Bike** [comment]
Fixed. We probably don't even need the warning but whatevs.
