### ISSUE TITLE
Superfluous or Duplicate Files in Repository

### ISSUE THREAD

**Issue by Bike** [drmeister/clasp#41]
Several files look like they're only included in the distribution accidentally.

* src/t.txt is some kind of clang session.
* src/chems is a tree structure of chemical names
* src/llvmo/ll.sh is a directory listing as from ls -l
* src/mpip/t.sh looks to be a command line from drmeister's personal environment
* src/asttooling/session.txt
* src/main/allHeaders_dump.cc* and unityBuild.cc* are series of includes of drmeister's absolute paths
* src/main/test.zzz
* src/main/t.sh
* src/core/exceptions.d has many drmeister absolute paths
* src/cando may be nanotech detritus
* src/main/all_debug.txt

will update if i notice more.

**Comment by Bike** [comment]
trawling src/core

* .gdb reads "hello"
* _Function empty
* _bjam.txt build record
* _compile_te_cmp.txt build record
* _dl.cxml couldn't even guess
* _profile.txt presumably profiling data, which I don't think belongs here
* a.csc
* a.make build record
* a.sed
* aaa.dat empty
* all_release.txt empty
* am4 some kind of wxWidgets thing for cando?
* argv.csc
* array0.lsp test code
* atomicWeights.txt
* b.csc
* bottom.txt
* bt.txt
* build-stacks.sh compiler invocation, mentions cando
* buildMany.py mentions cyclomers
* c
* candoClass.cc unless integration with nanotech is deeper than i thought; it references apparently nonexistent file candoClass.h
* ceil2.txt, presumably ceiling is actually implemented elsewhere
* change.sed here's hoping sed isn't part of the build process
* changeAll ditto and also mentions oligomers
* chemInfoParse.output
* chems buncha filenames
* cl.sh compiler invocation mentions cando
* class.cc.prototype mentions cando
* class.h.prototype ditto
* classInitialization.txt is notes, might be worth keeping, i don't know, but probably not here
* compile is a build record
* compile-symbolList.sh build command mentions cando
* compare.txt some kind of test?
* convert-vp0.el
* copyright maybe fine?
* copyrightAll maybe fine?
* cores buncha filenames
* def.csc m expressions!
* dielsAlderCyclomersFinal.cgd always good to get a refresher on orgo
* dmake got your email address
* docCommands.aux
* docCommands.tex
* docFilter.m4
* docs.template scores?
* dox.out build record
* doxygen.out build record
* dumpClasses.lsp cannot imagine what this is for
* e.lsp part of a formatter?
* ecl.lisp test code
* editDocs.* whole buncha shit that might have been cando docs at some point?
* environment.h.old
* evaluateEnergy.cc I'll be excited if optimization involves hessians
* example.doc some interesting salespersonship for cando
* exportedSymbols.txt
* f.csc
* fact.l test code
* fixHeader again, really hoping this isn't part of build
* fixInitialize
* fixVariadicMacros.m4
* fixes
* fixes.txt
* forceField.list
* forceField.txt
* foundation.cc not sure, but references cando and boost::python?
* foundation.h.pth empty
* foundation.hh might be legit but mentions some chemistry stuff
* g.csc
* gaffParse.output
* gamess.cc
* gl.csc
* globalOptions.csc seriously, are these corelscript or what?
* grep
* headerFiles.txt
* i.txt
* implementAmberFunction.cc
* improperRestraintTerms.cc
* indent.csc
* initClasses.inc no idea but looks generated
* initializeClasses.cc misspells "deprecated"
* initializeClassesWithWx.cc
* interactions.txt
* inv.csc
* key.csc
* lambdaListHandler consists of "c", probably a typo
* mainBoostPython.cc dunno what the hell this is
* make.log.part is over a megabyte and probably a build record
* makeDatabase.py cyclomers
* makeInitPythonCalls.awk
* makeInitPythonDeclares.awk
* makeSed.awk frightening filename
* makefile* possibly cando stuff
* matter.cc.old
* mbb* chemistry stuff
* ml.sh build command
* modified_lispLex.yy
* mpi*
* ms* is stuff for parsing SMILES or an extension of it or something

need food before looking at the rest
i'd like clasp to be understandable, and all these files floating around do not help that

**Comment by Shinmera** [comment]
There's probably new ones by now, so we should go through this again once there's a reproducible build.

**Comment by jorams** [comment]
Just to note some more things that *seem* useless, overlapping with @Bike's list:

- The `src/tests/old` directory
- Various `.tex` files and tex outputs in the `src/core` directory
- Various `.txt` files in the `src/core` directory
- A whole bunch of `.l` files in the `src/core` directory, that seem to have been used for testing
- A couple of `[a-z]{1,3}.csc` files in the `src/core` directory that are either useless or need a better name/location
- Various `.old` files, the `old` directory and the `oldArchive` directory in `src/core`
- All kinds of `test*.*` files in `src/core`
- `src/core/{.gdb,timing,am4,a.make,a.sed,TODO,_Function,aaa.dat`

**Comment by Shinmera** [comment]
Merging in from #45:

> See the list of file listed in https://bitbucket.org/faheem/clasp-debian/src/tip/rules
under the target override_dh_auto_clean: If these were moved into make clean, they
could be removed from debian/rules.

**Comment by Shinmera** [comment]
Is this resolved now from the changes in `dev-delete`?

**Comment by Georgiy-Tugai** [comment]
I believe that this has been resolved; I will, however, quote `rptb1`'s advice on the matter --
[`<rptb11> Make drmeister log in and get work done on a fresh account on a fresh computer :)`](http://irclog.tymoon.eu/freenode/clasp?around=2015-12-03T10:27:11&types=mnaot#1449138431)
