### ISSUE TITLE
Ansi tests: there is something wrong with signal-type-error

### ISSUE THREAD

**Issue by kpoeck** [drmeister/clasp#437]
Test case:
````
(delete-duplicates 0)
->
No value supplied for the initname "Type error"
````

**Comment by kpoeck** [comment]
Probably error is here:
````
(defun signal-type-error (type expected-type)
  (error 'type-error "type error"))
````

There must be missing an initarg, but I don't see which one

**Comment by Bike** [comment]
That's not even a valid `error` call. Bleh.

`signal-type-error` is defined very early in foundation.cc, so it doesn't have sensible lisp to work with. I'll see where else it's used and whether we can move it later to conditions.lsp, where it can make a proper condition.

**Comment by kpoeck** [comment]
fixed
