### ISSUE TITLE
Removing unneeded files from Clasp Debian package

### ISSUE THREAD

**Issue by fmitha** [drmeister/clasp#46]
[Here](https://gist.github.com/9aef43285aae31d5167f) is a list of the files in the Clasp Debian package.
Are all of these needed? In particular, are the Boost Build files necessary?

**Comment by Shinmera** [comment]
This should be properly documented somewhere to ease deployment to platforms in the future.

**Comment by Shinmera** [comment]
Closing since this is mostly outdated.
