### ISSUE TITLE
Add script to create tarball to upstream

### ISSUE THREAD

**Issue by fmitha** [drmeister/clasp#48]
The Debian package uses the script
https://bitbucket.org/faheem/clasp-debian/src/tip/git-archive-all.sh
(from https://github.com/meitar/git-archive-all.sh) to create an orig.tar.gz tarball
for use with package building. This script is a bit buggy, but could be fixed/improved.
I'd rather have a Python script, though.

In any case, I suggest this be moved into the main clasp repos, and perhaps a make target could
be added. Currently the command used to build the tarball is

    ./debian/rules get-orig-source

from the top level of the source directory, with the `debian/` directory copied in

The tarball specific part of the `get-orig-source` target could be made into a `tarball` target
in the main makefile, for use with packaging generally. Namely, the following lines

    ./debian/git-archive-all.sh --prefix clasp-0.1/ ../clasp_0.1.orig.tar
    gzip ../clasp_0.1.orig.tar

If the script was on the main level, this would look like

    ./git-archive-all.sh --prefix clasp-0.1/ ../clasp_0.1.orig.tar
    gzip ../clasp_0.1.orig.tar

Though having the `0.1` hardwired in there is of course, undesirable.

**Comment by Shinmera** [comment]
Since we're now using WAF a new issue to request this would be appropriate should the need arise.
