### ISSUE TITLE
Creating lib/dev Clasp Debian packages to compile the cxx demo against

### ISSUE THREAD

**Issue by fmitha** [drmeister/clasp#50]
A first step is to get necesary header and library files included in the Debian package. The libraries are easy, for now, anyway. They are static.

Here is a paste of all header files included in the clasp repos.
https://gist.github.com/605869a9136a8894d2aa

It would be helpful to have a list of top level headers that are required for building stuff (mostly C++ extensions, I suppose). Then one can presumably use some automated method for calculating a list of all header files that depend on those.

**Comment by fmitha** [comment]
As far as setting up an include heirarchy of header files inside the Clasp source code, there are two ways to go

1) Keep the header files in the same place as the source (*.cpp) files themselves. This would require more work in a 'make install' target. This is also possibly less standard. Someone (flash?) said this is not commonly done for C++ libraries.

2) Keep the headers in a separate directory hierarchy from the source files. This has the advantage that a make install target would then be a simple copy. However, the current makefile or whatever the build system is, would need to be adjusted. Also, having the headers and their corresponding source files in different places might making editing a little bit more work.

**Comment by drmeister** [comment]
I'm most of the way towards dealing with this issue.   All header files are now moved into the clasp/include/clasp hierarchy.  This could be installed in /usr/include/clasp on a target machine.

I think the next thing to do is to set up the libraries generated by clasp so that they can be installed in /usr/lib/clasp ??   Does that sound right?

**Comment by Shinmera** [comment]
I think all required header files are now in `clasp/include`.
