### ISSUE TITLE
Reloading .bundle not possible

### ISSUE THREAD

**Issue by HeyFlash** [drmeister/clasp#53]
Reloading .bundle files is not possible atm. Reloading .lsp files works. According to CLHS
http://www.lispworks.com/documentation/HyperSpec/Body/f_load.htm#load
load should behave (almost) equally regarding source and compiled files.

**Comment by Shinmera** [comment]
What's a bundle file? Is it generated by clasp somehow?

**Comment by drmeister** [comment]
Bundle files are FASL files - there is no limit now to the number of times they can be loaded.

**Comment by HeyFlash** [comment]
drmeister just beat me to it.
