### ISSUE TITLE
local.config.Linux in externals.clasp builds unusable clang 3.6 compiler

### ISSUE THREAD

**Issue by chriskmanx** [drmeister/clasp#55]
The comments in local.config.Linux of externals.clasp state that one can set GCC_EXECUTABLE and GXX_EXECUTABLE if gcc and g++ are not under GCC_TOOLCHAIN/bin. This suggests that these can be used instead of the GCC_TOOLCHAIN setting. externals.clasp will indeed build if following this advice, including clang 3.6. However, the resultant clang will be unable to link any executables, failing to find crtbegin.o from the gcclib-dev Linux package. It is indeed necessary to set  GCC_TOOLCHAIN to arrive at a usable clang, even if overriding the gcc executable locations. I suggest amending the comments to that effect. Also suggest to change Linux GCC_TOOLCHAIN  to /usr instead of $(HOME)/local/gcc-4.8.3. /usr is where common distributions like Ubuntu will place the system gcc. In this manner the configuration would "work out of the box" for anyone with a recent gcc.

Best Regards

Chris Kohlhepp

**Comment by Shinmera** [comment]
This is probably going to be remedied in tandem with #134

**Comment by Shinmera** [comment]
Externals clasp is no longer necessary for building.
