### ISSUE TITLE
get-universal-time returns unix time

### ISSUE THREAD

**Issue by stassats** [drmeister/clasp#56]
Which is 70 years too early, needs to add 2208988800 seconds.

**Comment by drmeister** [comment]
Much appreciated.

**Comment by Shinmera** [comment]
Can confirm on b05884f.

**Comment by drmeister** [comment]
Fixed in ba5377e20a80543e8af93f3ab39e1b4494e795bc

**Comment by Shinmera** [comment]
Fixed on 482d6ca5bd8ad30ff8c9b6a835989f3aec395e1a
```
> (get-universal-time)

3653128048
```
