### ISSUE TITLE
Ratio is not stored in a canonical form

### ISSUE THREAD

**Issue by stassats** [drmeister/clasp#58]
(/ -1 2) => -1/2 ;; right
(/ 1 -2) => 1/-2 ;; Not right
(/ -1 -2) => -1/-2 ;; really Not right
(/ 10 20) => 10/20 ;; Not right

**Comment by Shinmera** [comment]
Can confirm on b05884f.
```
> (/ -1 2)

-1/2
> (/ 1 -2)

1/-2
> (/ -1 -2)

-1/-2
> (/ 10 20) 

10/20
> 
```

**Comment by drmeister** [comment]
Ratios are normalized now when they are created.
