### ISSUE TITLE
bit vectors are not completely implemnted

### ISSUE THREAD

**Issue by stassats** [drmeister/clasp#64]
#*101
=>
#1A(COMMON-LISP:T NIL COMMON-LISP:T )

(aref #*101 0)
File(../../src/core/array.cc) lineNumber(189): Subclass[COMMON-LISP:SIMPLE-BIT-VECTOR] must implement method[aref] 

(sbit #*101 1) => NIL (should be 0)

(array-element-type  #*111)
File(../../src/core/lispVector.h) lineNumber(66): Subclass[COMMON-LISP:SIMPLE-BIT-VECTOR] must implement method[elementType]

**Comment by drmeister** [comment]
Should be all fixed now in "fixnum" branch.
