### ISSUE TITLE
multiple-value-call uses only the last argument for values

### ISSUE THREAD

**Issue by stassats** [drmeister/clasp#65]
(multiple-value-call #'list 1 2 3) => (3)
(multiple-value-call #'list (values 1 2 3)) => (1 2 3)
(multiple-value-call #'list (values 1 2 3) 1 2) => (2)

**Comment by drmeister** [comment]
This is a problem with my calling convention.  I need to fix this asap

**Comment by k--r** [comment]
this works for me now, in tag 0.3-test-6
so maybe this issue should be closed out ?

**Comment by stassats** [comment]
Doesn't work here.

**Comment by Shinmera** [comment]
Cannot confirm on b05884f.
```
> (multiple-value-call #'list 1 2 3)

(1 2 3)
> (multiple-value-call #'list (values 1 2 3)) 

(1 2 3)
> (multiple-value-call #'list (values 1 2 3) 1 2)

(1 2 3 1 2)
```
