### ISSUE TITLE
Macro Inlined Strings Are Not Properly Retrievable From EQUALP Hash-Table

### ISSUE THREAD

**Issue by Shinmera** [drmeister/clasp#74]
Minimal test case:
```commonlisp
(defvar *table* (make-hash-table :test 'equalp))
(defmacro define-foo (name) 
  `(setf (gethash ,(string name) *table*) ,(string name)))

(define-foo :bla)
(gethash "bla" *table*)
(gethash "BLA" *table*)
```

The first `gethash` call returns NIL, the second returns the proper value, but both should work.
Clasp build from adba6e4c808d85628c891e88eaf74a3940eb59b7

**Comment by drmeister** [comment]
I fixed this issue and pushed the change to the preview branch of github
