### ISSUE TITLE
(setf (get 'symbol 'key) value) fails

### ISSUE THREAD

**Issue by kpoeck** [drmeister/clasp#75]
Starting Clasp 0.11 ... loading image... it takes a few seconds
Top level.
> (setf (get 'foo 'bar) 42)

Condition of type: SIMPLE-PROGRAM-ERROR
There is no function bound to the symbol CORE::PUTPROP

Available restarts:
(use :r1 to invoke restart 1)

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

Broken at frame[15] LAMBDA.
 File: #<CORE:SOURCE-FILE-INFO #P"/Users/karstenpoeck/lisp/compiler/clasp/local-clasp/Contents/Resources/lisp/kernel/lsp/top.lsp"> (Position #573)
>> :r1

**Comment by kpoeck** [comment]
Seems to work in 0.2
CL-USER> (setf (get 'foo 'bar) 42)
42
CL-USER> (get 'foo 'bar)
42
CL-USER> (lisp-implementation-version)
"mps-0.2"
CL-USER> (lisp-implementation-type)
"Clasp"

**Comment by Shinmera** [comment]
Cannot confirm on b05884f.
```
> (setf (get 'foo 'bar) 0)

0
> (get 'foo 'bar)

0
> (get 'foo 'a)

NIL
```
