### ISSUE TITLE
(setf (symbol-plist 'foo) (list 'bar 42)) fails

### ISSUE THREAD

**Issue by kpoeck** [drmeister/clasp#76]
Starting Clasp 0.11 ... loading image... it takes a few seconds
Top level.

> (symbol-plist 'foo)

NIL

> (setf (symbol-plist 'foo) (list 'bar 42))

Condition of type: SIMPLE-PROGRAM-ERROR
There is no function bound to the symbol CORE::SET-SYMBOL-PLIST

Available restarts:
(use :r1 to invoke restart 1)
1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

Broken at frame[14] LAMBDA.
 File: #<CORE:SOURCE-FILE-INFO #P"/Users/karstenpoeck/lisp/compiler/clasp/local-clasp/Contents/Resources/lisp/kernel/lsp/top.lsp"> (Position #573)

> > :r1

**Comment by Shinmera** [comment]
Can confirm on b05884f.
```
> (setf (symbol-plist 'foo) (list 'bar 42))
;;; Warning: Condition: Undefined function named CORE:SET-SYMBOL-PLIST

Condition of type: SIMPLE-PROGRAM-ERROR
Could not find function CORE:SET-SYMBOL-PLIST
```

**Comment by Bike** [comment]
On 35f15d4, the setf works

```
> (symbol-plist 'foo)
NIL
> (setf (symbol-plist 'foo) (list 'bar 42))
; No value
> (symbol-plist 'foo)
(BAR 42)
```

...except that it should return the value it's being set to.

**Comment by kpoeck** [comment]
Works fine with now Clasp "cclasp-boehm-FRGO_CLASP_DEV_FOREIGN_DATA_002-1212-g7a6472a72" git branch testing date 2017-07-01
