### ISSUE TITLE
apropos with optional parameter package segfaults

### ISSUE THREAD

**Issue by kpoeck** [drmeister/clasp#78]
karstenoecksMBP:program karstenpoeck$  ../../compiler/clasp/local-clasp/MacOS/clasp_mps_o 
Starting Clasp 0.11 ... loading image... it takes a few seconds
Top level.
> (apropos "DEFUN" (find-package :cl))
Segmentation fault: 11

**Comment by kpoeck** [comment]
Sorry this is a duplicate to 52

**Comment by Shinmera** [comment]
Cannot confirm on b05884f.
```
> (apropos "DEFUN" (find-package :cl))
DEFUN  Macro
```
