### ISSUE TITLE
homebrew formula

### ISSUE THREAD

**Issue by trashhalo** [drmeister/clasp#8]
Any chance of a homebrew formula that encapsulates the installation steps?

https://github.com/Homebrew/homebrew/wiki/Formula-Cookbook

**Comment by Shinmera** [comment]
Needs to be reevaluated as per #135

**Comment by GOFAI** [comment]
Looking at homebrew's build process, I was wondering if it might be possible to create a homebrew formula that uses the llvm-3.6 formula provided by the homebrew-versions tap and its associated clang instead of the one built by externals-clang or the one that comes with XCode.
