### ISSUE TITLE
Clasp should be building against llvm 3.6, but isn't

### ISSUE THREAD

**Issue by fmitha** [drmeister/clasp#81]
When attempting to build clasp against llvm 3.6 rc (forked from trunk around 2 weeks ago),
I got
```
Error: In file included from gc_interface.cc:153:
03:39 <faheem_> ../../include/clasp/llvmo/llvmoExpose.h:53:10: fatal error: 'llvm/Analysis/TargetLibraryInfo.h' file not found
```

So the problem was with
```
#include <llvm/Analysis/TargetLibraryInfo.h>
```

But the version in my 3.6 rc was:
```
dpkg -S TargetLibraryInfo.h
llvm-3.6-dev: /usr/include/llvm-3.6/llvm/Target/TargetLibraryInfo.h
```

I then found http://reviews.llvm.org/rL226078
which showed this change had been made around 2 weeks ago.
It seemed unlikely this change had been made right at the time of an rc, so I asked on
#llvm. My guess was confirmed
```
03:49 <faheem> Hi, I have a quick question about llvm.
03:49 <faheem> If some code is using <llvm/Analysis/TargetLibraryInfo.h>, then can someone confirm that is 3.7?
03:50 <faheem> Because I found http://reviews.llvm.org/rL226078, which sort of suggests that this path corresponds to 3.7.
03:50 <faheem> that was around the time of the rc, i believe.
03:58 <bogner> faheem: That was moved after the 3.6 branch, yes.
```
Conclusion. The clang/llvm in externals is the 3.7 branch and needs to be moved back to 3.6.

**Comment by Shinmera** [comment]
Should be fixed in tandem with #134
