### ISSUE TITLE
If user has boost-build installed in /usr/share/boost-build bjam tries to use its .jam files

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#82]
I must figure out how to disable this behavior in bjam
Here someone is describing the same problem: http://lists.boost.org/boost-build/2007/08/17017.php

A work around is to temporarily rename the /usr/share/boost-build directory

**Comment by drmeister** [comment]
I don't think this will be an issue anymore.  I don't use a hacked version of boost build anymore - so even if an installed version of boost-build exists - their version should work for building Clasp.

**Comment by Shinmera** [comment]
Closing for now.
