### ISSUE TITLE
Arbitrary number of blank lines in C++ source lispStream.cc

### ISSUE THREAD

**Issue by robert-strandh** [drmeister/clasp#87]
In the file lispStream.cc the number of blank lines that separate some
function definitions seems to be quite arbitrary.  Mostly there is a
single blank line, but sometimes there is none, and sometimes there is
up to four.  While the number of blank lines does not affect how the
final system works, it gives a bad impression.  Certainly, it
distracts some readers from the essence of the code, which is probably
not a desired effect.

**Comment by Shinmera** [comment]
Should be fixed with #88

**Comment by Shinmera** [comment]
Indeed, clang-format fixes this. Should be good as of 6c8242eb3a6bf3ac4a2301b259acb8c6d53fb994
