### ISSUE TITLE
Aribtrary spacing in C++ source code.

### ISSUE THREAD

**Issue by robert-strandh** [drmeister/clasp#88]
The spacing in some C++ seems quite arbitrary.  For instance, in the
file lispStram.cc, the condition in an if statement is sometimes
surrounded by spaces as the first if statement in the function
AnsiStreamTypeP, and sometimes not, as in the second if statement in
the same function.

While the spacing does not affect the way the final system works, it
gives a bad impression and it distracts the reader from the more
important aspects of the code.

**Comment by robert-strandh** [comment]
In the same file, the operator && is sometimes surrounded by spaces,
and sometimes not.

**Comment by Shinmera** [comment]
Should hopefully be fixed coming week by a run of clang-format, as done in #97.

**Comment by drmeister** [comment]
SAL9000 ran clang-format on the source code and I merged it into dev and testing branches. 
It's in as of https://github.com/drmeister/clasp/commit/6c8242eb3a6bf3ac4a2301b259acb8c6d53fb994

**Comment by Shinmera** [comment]
Looks good to me.
